"use client";
import { useEffect, useMemo, useRef, useState } from 'react';

import { flushSync } from 'react-dom';
import { ArrowRight, ArrowUpRight, Check, ChevronLeft, ChevronRight, CircleHelp, Code2, Layers3, Lightbulb, Pause, Play, RotateCcw, Sparkles } from 'lucide-react';
import { encode, tokenize, CONFIG } from '@/lib/transformer/engine';
import { steps } from '@/lib/transformer/steps';
import { learningModules } from '@/lib/modules';
import { Attention, MatrixView, Vector, Visualization } from '@/components/lab/visualization';

type ModelContext = {registerTool:(tool:{name:string;title:string;description:string;inputSchema:object;annotations:object;execute:(input:unknown)=>unknown},options:{signal:AbortSignal})=>void|Promise<void>};
const examples=['我 喜欢 学习 人工 智能','猫 坐 在 柔软 的 垫子 上','The cat sat on the mat'];
export default function Home(){
  const [draft,setDraft]=useState(examples[0]);
  const [text,setText]=useState(examples[0]);
  const [step,setStep]=useState(0);
  const [query,setQuery]=useState(0);
  const [head,setHead]=useState(0);
  const [playing,setPlaying]=useState(false);
  const [speed,setSpeed]=useState(1);
  const [error,setError]=useState('');
  const [help,setHelp]=useState(false);
  const model=useMemo(()=>encode(text),[text]);
  const selected=steps[step];
  const inputRef=useRef<HTMLInputElement>(null);
  const helpRef=useRef<HTMLDialogElement>(null);
  const helpButtonRef=useRef<HTMLButtonElement>(null);
  const stateRef=useRef({step,text});stateRef.current={step,text};
  const n=model.tokens.length;
  const go=(index:number)=>{setStep(Math.max(0,Math.min(steps.length-1,index)));setPlaying(false);};
  const selectQuery=(index:number)=>{setQuery(index);setPlaying(false);};
  const run=(value=draft)=>{if(!tokenize(value).length){setError('先输入一句文本，再开始探索。');inputRef.current?.focus();return;}setText(value);setDraft(value);setQuery(0);setHead(0);setStep(1);setPlaying(false);setError('');};
  useEffect(()=>{if(!playing)return;if(step===steps.length-1){setPlaying(false);return;}const timer=setTimeout(()=>setStep(v=>Math.min(v+1,steps.length-1)),3400/speed);return()=>clearTimeout(timer);},[playing,step,speed]);
  useEffect(()=>{const handle=(e:KeyboardEvent)=>{const target=e.target as HTMLElement;if(help||target.closest('input,textarea,select,button,a,[contenteditable]'))return;if(e.key==='ArrowRight'){e.preventDefault();setStep(v=>Math.min(v+1,10));setPlaying(false);}if(e.key==='ArrowLeft'){e.preventDefault();setStep(v=>Math.max(v-1,0));setPlaying(false);}if(e.code==='Space'){e.preventDefault();setPlaying(v=>!v);}};window.addEventListener('keydown',handle);return()=>window.removeEventListener('keydown',handle);},[help]);
  useEffect(()=>{if(help){setPlaying(false);helpRef.current?.showModal();}else if(helpRef.current?.open){helpRef.current.close();helpButtonRef.current?.focus();}},[help]);
  useEffect(()=>{const context=(document as Document & {modelContext?:ModelContext}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();try{void Promise.resolve(context.registerTool({name:'navigate_transformer_step',title:'切换 Transformer 教学步骤',description:'将实验室切换到 1–11 中的一个教学步骤并暂停自动播放。',inputSchema:{type:'object',properties:{step:{type:'integer',minimum:1,maximum:11}},required:['step'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(typeof input!=='object'||input===null||!('step' in input)||!Number.isInteger(input.step)||Number(input.step)<1||Number(input.step)>11||Object.keys(input).some(k=>k!=='step'))throw new Error('step 必须是 1–11 的整数。');const next=Number(input.step)-1;flushSync(()=>{setStep(next);setPlaying(false);});return{step:stateRef.current.step+1,title:steps[stateRef.current.step].title};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();},[]);
  const matrix=step===2?model.embedding:step===3?model.x:step===4?model.heads[head].q:step===5?model.heads[head].scores:step===6||step===7?model.heads[head].attention:step===8?model.norm1:step===9?model.ffn:model.output;
  const matrixLabel=step===2?'嵌入矩阵 E':step===3?'位置感知表示 X':step===4?`查询矩阵 Q · Head ${head+1}`:step===5?'匹配分数 S':step===6||step===7?`注意力矩阵 A · Head ${head+1}`:step===8?'归一化表示 H':step===9?'前馈输出 F':'上下文表示 Y';
  return <div className="lab">
    <header className="topbar"><a className="brand" href="/" aria-label="Transformer Lab 首页"><span className="brand-icon"><Layers3 size={23}/></span>Transformer <span className="brand-light">Lab</span></a><nav className="mode-nav" aria-label="学习模式"><a href="/" aria-current="page">Transformer 层内流程</a><a href="/generation">LLM 生成模式</a><a href="/training">模型训练实验室</a><a href="/build-model">从零造模</a></nav><div className="topbar-end"><span className="version">ENCODER / 01</span><button ref={helpButtonRef} className="icon-button" aria-label="学习指南" onClick={()=>setHelp(true)}><CircleHelp size={20}/></button></div></header>
    <aside className="sidebar"><div className="section-label">学习路径</div><h3>走进 Transformer</h3><nav aria-label="Transformer 计算步骤">{steps.map((s,i)=><button aria-current={step===i?'step':undefined} className={step===i?'step active':i<step?'step completed':'step'} key={s.id} onClick={()=>go(i)}><span className="step-number">{i<step?<Check size={13}/>:String(i+1).padStart(2,'0')}</span><span>{s.title}<small>{s.en}</small></span>{i===step&&<ChevronRight size={16}/>}</button>)}</nav><div className="sidebar-foot"><span className="section-label">未来的实验</span><div className="future-modules">{learningModules.filter(m=>!m.available).map(m=><span key={m.id}>{m.label}</span>)}</div><small>扩展模块 · 尚未开放</small></div></aside>
    <main className="main"><div className="page-heading"><div><div className="eyebrow"><span/> INTERACTIVE MODEL EXPLORER</div><h1>让每一步计算，<span>看得见。</span></h1><p className="intro">从一句话到上下文表示，亲手探索 Transformer 的内部世界。</p></div><span className="model-label"><Code2 size={16}/> 单层 Encoder</span></div>
      <section className="input-panel" aria-label="输入实验文本"><div className="input-label-row"><label htmlFor="sentence">从一句话开始</label><span>空格分词 · 无空格中文按字拆分</span></div><form className="input-row" onSubmit={e=>{e.preventDefault();run();}}><input ref={inputRef} id="sentence" value={draft} onChange={e=>{setDraft(e.target.value);setError('');}} maxLength={240} placeholder="例如：我 喜欢 学习 人工 智能" aria-invalid={!!error} aria-describedby="input-hint"/><button className="primary" type="submit">开始探索 <ArrowRight size={16}/></button></form><div className="input-bottom"><div className="examples"><span>试一试</span>{examples.slice(1).map((s,i)=><button key={s} onClick={()=>run(s)}>{i===0?'猫与垫子':'英文句子'}<ArrowUpRight size={12}/></button>)}</div><span id="input-hint" className={error||model.truncated?'input-warning':'input-hint'} role={error?'alert':undefined}>{error|| (model.truncated?`共 ${model.allTokens.length} 个 token，当前仅演示前 ${CONFIG.maxTokens} 个。`:`${n} TOKENS · 最多演示 10 个`)}</span></div></section>
      <div className="mobile-steps"><label htmlFor="step-select">当前步骤</label><select id="step-select" value={step} onChange={e=>go(Number(e.target.value))}>{steps.map((s,i)=><option key={s.id} value={i}>{String(i+1).padStart(2,'0')} · {s.title}</option>)}</select></div>
      <div className="studio-grid"><section className="workspace" aria-label="动态数据流"><div className="canvas-header"><div className="stage-title"><span className="stage-number">{String(step+1).padStart(2,'0')}</span><div><h2>{selected.title}</h2><span>{selected.en}</span></div></div><span className="pill">{n} tokens × 8 dims</span></div><div className="canvas-toolbar"><span><i className="live-dot"/> {playing?'正在播放数据流':'探索数据流'}</span>{step>=4&&step<=7?<div className="head-switch" aria-label="注意力头">{[0,1].map(i=><button key={i} aria-pressed={i===head} className={i===head?'selected':''} onClick={()=>{setHead(i);setPlaying(false);}}>Head {i+1}</button>)}</div>:<span className="subtle-meta">{step===0?'11 个步骤 · 逐步理解':'固定种子 · 实时计算'}</span>}</div>
        <div className="stage-canvas" key={step}><Visualization step={step} model={model} query={query} head={head} onQuery={selectQuery}/></div>
        {step>=3&&step!==5&&step!==6&&<div className="token-selector"><span>观察 token</span>{model.tokens.map((t,i)=><button key={i} aria-pressed={query===i} className={query===i?'selected':''} onClick={()=>selectQuery(i)} title={`位置 ${i}`}>{t}<small>{i}</small></button>)}</div>}
        <div className="flow-strip" aria-hidden="true">{['文本','向量','位置','注意力','FFN','表示'].map((s,i)=>{const groups=[0,2,3,4,9,10];const active=groups.reduce((a,v,j)=>step>=v?j:a,0)===i;return <span key={s} className={active?'selected':''}>{s}{i<5&&<ChevronRight size={12}/>}</span>})}</div>
        <div className="controls"><button className="icon-button reset" aria-label="重置为第一步" title="重置为第一步" onClick={()=>{go(0);setQuery(0);setHead(0);}}><RotateCcw size={17}/></button><div className="playback"><button aria-label="上一步" disabled={step===0} onClick={()=>go(step-1)}><ChevronLeft size={16}/><span>上一步</span></button><button className="primary play-button" onClick={()=>{if(step===10)setStep(0);setPlaying(v=>!v);}}>{playing?<Pause size={15}/>:<Play size={15}/>} {playing?'暂停':step===10?'重新播放':'自动播放'}</button><button aria-label="下一步" disabled={step===10} onClick={()=>go(step+1)}><span>下一步</span><ChevronRight size={16}/></button></div><label className="speed-control"><span className="sr-only">播放速度</span><select aria-label="播放速度" value={speed} onChange={e=>setSpeed(Number(e.target.value))}><option value={.5}>0.5×</option><option value={1}>1×</option><option value={2}>2×</option></select></label></div><div className="progress-track"><span style={{width:`${(step+1)/steps.length*100}%`}}/></div>
      </section>
      <aside className="inspector" aria-label="步骤说明"><div className="inspector-label"><span>理解这一步</span><span>{String(step+1).padStart(2,'0')} / 11</span></div><div className="explanation" key={step}><h2>{selected.title}</h2><p>{selected.description}</p><div className="formula-section"><div className="detail-label"><Code2 size={14}/> 核心公式</div><pre>{selected.formula}</pre></div><div className="shape-section"><div className="detail-label"><Layers3 size={14}/> 张量维度</div><code>{selected.shape(n)}</code><small>n = {n} · d_model = 8 · h = 2 · dₖ = 4<br/>省略 batch 维；本例 batch = 1</small></div><div className="insight"><Lightbulb size={17}/><div><b>理解小提示</b><p>{selected.insight}</p></div></div></div></aside></div>
      <div className="below-grid"><section className="data-panel"><div className="panel-heading"><h3>{step<2?'一眼看懂这次实验':matrixLabel}</h3><span className="subtle-meta">{step<2?'MODEL CONFIGURATION':'点击行标签切换 token · 悬停查看数值'}</span></div>{step<2?<div className="configuration"><div><b>{n.toString().padStart(2,'0')}</b><span>输入 token</span></div><div><b>08</b><span>向量维度</span></div><div><b>02</b><span>注意力头</span></div><div><b>01</b><span>Encoder 层</span></div></div>:<MatrixView data={matrix} rows={model.tokens} selected={query} onSelect={selectQuery} probability={step===6||step===7} tokenColumns={step>=5&&step<=7} label={matrixLabel}/>}</section><section className="observation"><div className="panel-heading"><h3>{step===10?'这一层，学到了什么？':'实验观察'}</h3><Sparkles size={17}/></div>{step>=5&&step<=7?<><div className="observation-token">{model.tokens[query]} <span>正在查询</span></div><div className="weight-bars">{model.tokens.map((t,i)=><div key={i}><span title={t}>{t}</span><div><i style={{width:`${model.heads[head].attention[query][i]*100}%`}}/></div><code>{(model.heads[head].attention[query][i]*100).toFixed(1)}%</code></div>)}</div><small>Head {head+1} 的 Softmax 权重，每行总和为 1。</small></>:step===10?<><p>每个 token 都从其他位置收集了信息，得到新的上下文向量。</p><div className="compare-vector"><span>输入 X</span><Vector values={model.x[query]}/></div><div className="compare-vector"><span>输出 Y</span><Vector values={model.output[query]}/></div><small>数值发生变化 ≠ 已学会语言。真实模型需要训练。</small></>:<><div className="observation-icon"><Layers3 size={25}/></div><p>{step<2?'文字如何变成模型能够处理的数字？点击“下一步”，从分词开始。':'选择不同 token，对比它们的数值；所有颜色都对应当前计算结果。'}</p><div className="observation-tag">{step<2?'从输入到表示，全程可追踪':'蓝色为正 · 橙色为负 · 深浅表示幅度'}</div></>}</section></div>
      {step===7&&<section className="head-detail"><div className="panel-heading"><h3>看看当前注意力头如何连接 token</h3><span>Head {head+1}</span></div><Attention model={model} query={query} head={head} scores={false} onQuery={selectQuery}/></section>}
      {step===10&&<div className="generation-bridge"><div><b>有了输出表示，怎样生成下一个 token？</b><p>进入因果 Decoder，探索 LM Head、采样与 KV Cache。</p></div><a href="/generation">进入 LLM 生成模式 <ArrowRight size={17}/></a></div>}<footer className="page-footer"><span>教学演示 · 固定随机参数，未训练 · 本地计算，不上传输入文本</span><a href="https://arxiv.org/abs/1706.03762" target="_blank" rel="noreferrer">原论文 <ArrowUpRight size={12}/></a></footer>
      <span className="sr-only" role="status" aria-live="polite">第 {step+1} 步，共 11 步：{selected.title}</span>
    </main>
    <dialog ref={helpRef} className="help-dialog" onCancel={()=>setHelp(false)} onClick={e=>{if(e.target===e.currentTarget)setHelp(false);}}><div className="dialog-heading"><h2>你的 Transformer 实验指南</h2><button aria-label="关闭学习指南" onClick={()=>setHelp(false)}>关闭</button></div><p>这是一个单层、双向、Post-LN Encoder。用较小的真实矩阵计算，展示完整的信息流动。</p><ol><li>输入文本，点击“开始探索”。中文可以用空格分词，最多显示 10 个 token。</li><li>用上一步、下一步或自动播放，顺着计算路径前进；也可直接点击左侧步骤。</li><li>在注意力步骤点击 token、切换注意力头，对照连线与热力图。</li></ol><p><b>键盘：</b>页面空白处使用 ← / → 切换步骤，空格播放或暂停。表单与按钮保留各自的键盘行为。</p><p className="dialog-note">这是未训练的演示模型，权重不代表词义关系。输出是向量表示；生成文字还需要 Decoder 或语言模型输出头。演示省略 dropout、嵌入缩放和 batch 维。</p></dialog>
  </div>;
}



