"use client";
import { useEffect, useMemo, useState } from 'react';

import { ArrowRight, ChevronLeft, ChevronRight, Database, Layers3, Pause, Play, Repeat2, RotateCcw, ShieldCheck } from 'lucide-react';
import { tokenize } from '@/lib/transformer/engine';
import { DEFAULT_SAMPLING, distribution, VOCAB, type DecoderResult, type Sampling } from '@/lib/generation/engine';
import { backward, forward, startSession, toggleCache, type Session } from '@/lib/generation/session';
import { generationSteps } from '@/lib/generation/steps';
import { Vector } from './visualization';

function CausalAttention({result,head}:{result:DecoderResult;head:number}) {
  const n=result.tokens.length;
  const width=Math.max(660,(n+1)*70+40);
  const x=(i:number)=>40+i*(width-130)/Math.max(n,1);
  const qx=x(n-1)/2+20;
  const probs=result.heads[head].attention[n-1];
  return <div className="causal-attention"><div className="gen-caption"><span>最后一个 token 的 Query</span><span>Head {head+1} · Σ 权重 = {probs.reduce((a,b)=>a+b,0).toFixed(3)}</span></div><div className="gen-scroll"><svg viewBox={`0 0 ${width} 235`} style={{minWidth:width}} role="img" aria-label="最后一个 token 对已有上下文的注意力，未来 token 不可见"><rect x={qx-50} y="10" width="100" height="36" rx="9" fill="#5a6de4"/><text x={qx} y="34" fill="white" textAnchor="middle">Q · {result.tokens[n-1].slice(0,5)}</text>{probs.map((p,i)=><g key={i}><path d={`M ${qx} 47 C ${qx} 95, ${x(i)} 90, ${x(i)} 146`} fill="none" stroke="#7d8ce6" strokeWidth={1+12*p} opacity={.3+.7*p}/><path className="flow-dash" d={`M ${qx} 47 C ${qx} 95, ${x(i)} 90, ${x(i)} 146`} fill="none" stroke="#5e75d6" strokeWidth="1" strokeDasharray="3 12"/><rect x={x(i)-29} y="147" width="58" height="35" rx="6" fill={i===n-1?'#eaf6f2':'white'} stroke={i===n-1?'#70b9a4':'#d9e1f1'}/><text x={x(i)} y="169" textAnchor="middle" fill="#4c6083">{result.tokens[i].slice(0,4)}</text><text x={x(i)} y="206" textAnchor="middle" fill="#798cba">{(p*100).toFixed(1)}%</text></g>)}<rect x={x(n)-31} y="147" width="65" height="35" rx="6" fill="#f5f6fa" stroke="#a6afc0" strokeDasharray="4 4"/><text x={x(n)} y="169" textAnchor="middle" fill="#97a2b8">未来 ?</text><text x={x(n)} y="206" textAnchor="middle" fill="#97a2b8">不可见</text></svg></div><p className="gen-footnote">最后一个 token 可以关注自己。虚线框不是输入，不参与当前注意力计算。</p></div>;
}
function Mask({result,head}:{result:DecoderResult;head:number}) {
  const n=result.tokens.length;
  return <section className="mask-panel"><div className="panel-heading"><h3><ShieldCheck size={16}/> Causal Mask · 只能看左侧与自己</h3><span className="subtle-meta">行 = Query，列 = Key</span></div><div className="gen-scroll"><div className="causal-grid" style={{gridTemplateColumns:`52px repeat(${n}, 30px)`}}><span>Q / K</span>{result.tokens.map((t,j)=><span className="mask-label" title={`${t} · 位置 ${j}`} key={`k${j}`}>{j}</span>)}{result.tokens.map((t,i)=><div className="matrix-row" key={i}><span className={i===n-1?'last-label':'mask-label'} title={`${t} · 位置 ${i}`}>{t.slice(0,3)}<small>{i}</small></span>{result.tokens.map((_,j)=><span key={j} className={`mask-cell ${j>i?'blocked':'allowed'} ${i===n-1?'last-row':''}`} title={j>i?`Q${i} → K${j}：未来位置，遮罩 −∞，Softmax 后为 0`:`Q${i} → K${j}：${(result.heads[head].attention[i][j]*100).toFixed(2)}%`} aria-label={j>i?`位置 ${i} 看位置 ${j}：已遮罩`:`位置 ${i} 看位置 ${j}：允许`}>{j>i?'×':i===n-1?'●':'·'}</span>)}</div>)}</div></div><div className="mask-legend"><span><i/> 可见（包括自己）</span><span><i className="blocked"/> 未来遮罩 −∞ → 权重 0</span><span>绿色边框：最后一个 Query</span></div></section>;
}
function CachePanel({session,result}:{session:Session;result:DecoderResult}) {
  const n=result.tokens.length;
  const previous=n===session.prompt.length?0:n-1;
  const incremental=n-previous;
  return <section className="cache-panel"><div className="panel-heading"><h3><Database size={16}/> KV Cache · 把计算留给新 token</h3><span className="cache-phase">{previous===0?'PREFILL · 首次处理完整提示':'DECODE · 逐 token 解码'}</span></div><div className="cache-comparison">{[false,true].map(enabled=><div key={String(enabled)} className={`cache-lane ${session.cacheEnabled===enabled?'current':''}`}><div className="lane-title"><b>{enabled?'有缓存':'无缓存'}</b><span>{session.cacheEnabled===enabled?'当前执行':'同轮对照'}</span></div><div className="cache-token-list">{result.tokens.map((t,i)=><span title={`${t} #${i}：${enabled&&i<previous?'复用 K/V':'重新投影 Q/K/V'}`} className={enabled&&i<previous?'reused':'computed'} key={i}>{t.slice(0,5)}<small>{enabled&&i<previous?'复用 K/V':'计算 QKV'}</small></span>)}</div><div className="cache-stats"><span>新投影 <b>{enabled?incremental:n}</b> 个 token</span><span>QK 点积 <b>{2*(enabled?incremental:n)*n}</b> 次</span></div></div>)}</div><div className="cache-store"><span>K cache <code>[2, {session.cacheEnabled?n:0}, 4]</code></span><span>V cache <code>[2, {session.cacheEnabled?n:0}, 4]</code></span><span>当前执行：复用 {result.reused}，计算 {result.computed}</span></div><p className="gen-footnote">缓存复用的是 K、V，不缓存 Q。仍需计算新 Query 与全部历史 Key 的注意力。点积计数包含遮罩前的完整矩阵计算，非耗时测量；关闭缓存时不跨轮复用。首轮没有历史缓存，两种路径相同。</p></section>;
}

export default function GenerationLab(){
  const [draft,setDraft]=useState('我 喜欢 学习');
  const [session,setSession]=useState(()=>startSession(tokenize('我 喜欢 学习')));
  const [playing,setPlaying]=useState<'off'|'round'|'continuous'>('off');
  const [speed,setSpeed]=useState(1);
  const [head,setHead]=useState(0);
  const [error,setError]=useState('');
  const f=session.frames[session.cursor];
  const lesson=generationSteps[f.phase];
  const result=f.result;
  const candidates=useMemo(()=>distribution(result.logits,session.sampling),[result,session.sampling]);
  const visibleContext=[...session.prompt,...f.generated];
  const displayGenerated=f.generated.filter(t=>t!=='[EOS]');
  const round=f.phase===7?f.generated.length:f.generated.length+1;
  const stop=()=>setPlaying('off');
  const next=()=>{stop();setSession(forward);};
  const prev=()=>{stop();setSession(backward);};
  const restart=()=>{stop();setSession(startSession(session.prompt,session.sampling,session.cacheEnabled));};
  function applyPrompt(){const tokens=tokenize(draft);if(!tokens.length||tokens.length>12){setError('请输入 1–12 个 token；用空格分词，无空格中文按字拆分。');stop();return;}stop();setError('');setSession(startSession(tokens,session.sampling,session.cacheEnabled));}
  function changeSampling(patch:Partial<Sampling>){stop();setSession(startSession(session.prompt,{...session.sampling,...patch},session.cacheEnabled));}
  useEffect(()=>{if(playing==='off')return;if(f.stop||(playing==='round'&&f.phase===7)){setPlaying('off');return;}const id=setTimeout(()=>setSession(forward),1600/speed);return()=>clearTimeout(id);},[playing,speed,f]);
  useEffect(()=>{function key(e:KeyboardEvent){if((e.target as HTMLElement).closest('input,select,button,a,textarea'))return;if(e.key==='ArrowRight'){e.preventDefault();setPlaying('off');setSession(forward);}if(e.key==='ArrowLeft'){e.preventDefault();setPlaying('off');setSession(backward);}}window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
  const beginPlay=(kind:'round'|'continuous')=>{if(f.stop)return;if(playing===kind){stop();return;}if(f.phase===7)setSession(forward);setPlaying(kind);};
  const maxLogit=Math.max(...result.logits.map(Math.abs),1);
  return <div className="generation-lab"><header className="topbar"><a className="brand" href="/"><span className="brand-icon"><Layers3 size={23}/></span>Transformer <span className="brand-light">Lab</span></a><nav className="mode-nav" aria-label="学习模式"><a href="/">Transformer 层内流程</a><a href="/generation" aria-current="page">LLM 生成模式</a><a href="/training">模型训练实验室</a><a href="/build-model">从零造模</a></nav></header><main className="generation-main">
    <div className="page-heading"><div><div className="eyebrow"><span/> NEXT TOKEN GENERATION</div><h1>一句话，<span>是怎样接着写下去的？</span></h1><p className="intro">最后一个表示 → 下一个 token → 新的上下文。亲手走完自回归生成的循环。</p></div><span className="gen-model-badge">Causal Decoder · 2 Heads · 24 Vocab</span></div>
    <section className="gen-input input-panel"><form className="input-row" onSubmit={e=>{e.preventDefault();applyPrompt();}}><label htmlFor="gen-prompt">起始提示</label><input id="gen-prompt" value={draft} maxLength={240} onChange={e=>{setDraft(e.target.value);setError('');}} aria-describedby="gen-input-hint" aria-invalid={!!error}/><button className="primary" type="submit">开始新实验 <ArrowRight size={16}/></button></form><p id="gen-input-hint" className={error?'gen-error':'gen-footnote'} role={error?'alert':undefined}>{error||'空格分词；无空格中文按字拆分。最多输入 12 个 token。演示参数未训练，输出不保证有意义。'}</p></section>
    <section className="context-board" aria-label="实时上下文"><div><div className="gen-caption"><b>当前输入上下文</b><span>{visibleContext.length} / 24 TOKENS</span></div><div className="context-tokens">{visibleContext.map((t,i)=><span className={`${i>=session.prompt.length?'generated':''} ${i===visibleContext.length-1?'last':''}`} key={i}>{t}<small>{i}</small></span>)}</div><small>紫色：原始提示　绿色：已生成 token　边框：当前最后位置</small></div><div className="generated-board"><div className="gen-caption"><b>当前已生成文本</b><span>{f.generated.length} / {session.sampling.maxNew}</span></div><output data-testid="generated-text" aria-live="polite">{displayGenerated.length?displayGenerated.join(' '):<span className="empty-generation">下一个 token，即将出现<span className="text-caret"/></span>}</output>{f.generated.includes('[EOS]')&&<span className="eos-badge">EOS · 结束符</span>}<small>{f.phase===7?'已追加；下一轮才会把新 token 写入 K/V。':`第 ${round} 轮：使用 ${result.tokens.length} 个 token 预测下一项。`}</small></div></section>
    <section className="sampling-panel" aria-label="采样设置"><label>采样策略<select aria-label="采样策略" value={session.sampling.method} onChange={e=>changeSampling({method:e.target.value as Sampling['method']})}><option value="greedy">Greedy · 最大值</option><option value="top-k">Top-k · 固定候选数</option><option value="top-p">Top-p · 累计概率</option><option value="temperature">Temperature · 全词表采样</option></select></label><label><span>温度 T <b>{session.sampling.temperature.toFixed(1)}</b></span><input aria-label="温度" type="range" min="0.1" max="2" step="0.1" value={session.sampling.temperature} disabled={session.sampling.method==='greedy'} onChange={e=>changeSampling({temperature:Number(e.target.value)})}/></label><label>Top-k<select aria-label="Top-k" value={session.sampling.k} disabled={session.sampling.method!=='top-k'} onChange={e=>changeSampling({k:Number(e.target.value)})}>{[1,3,5,8,12,24].map(k=><option key={k}>{k}</option>)}</select></label><label>Top-p<select aria-label="Top-p" value={session.sampling.p} disabled={session.sampling.method!=='top-p'} onChange={e=>changeSampling({p:Number(e.target.value)})}>{[.3,.5,.7,.9,.95,1].map(p=><option key={p}>{p}</option>)}</select></label><label>最多生成<select aria-label="最多生成" value={session.sampling.maxNew} onChange={e=>changeSampling({maxNew:Number(e.target.value)})}>{[2,4,6,8,12].map(v=><option value={v} key={v}>{v} tokens</option>)}</select></label><label>随机种子<select aria-label="随机种子" value={session.sampling.seed} onChange={e=>changeSampling({seed:Number(e.target.value)})}>{[42,7,123,2026].map(v=><option key={v}>{v}</option>)}</select></label><label className="cache-toggle"><input type="checkbox" checked={session.cacheEnabled} onChange={e=>{stop();setSession(s=>toggleCache(s,e.target.checked));}}/><span><Database size={17}/> KV Cache</span></label><p>修改采样设置将重新开始；切换缓存保留当前进度与采样结果。{session.sampling.method==='greedy'?' Greedy 忽略温度。':''}</p></section>
    <div className="generation-player"><div className="round-badge">ROUND <b>{String(round).padStart(2,'0')}</b><span>{f.phase+1} / 8</span></div><div className="generation-controls"><button aria-label="生成上一步" disabled={session.cursor===0} onClick={prev}><ChevronLeft size={16}/>上一步</button><button aria-label="生成下一步" disabled={!!f.stop} onClick={next}>下一步<ChevronRight size={16}/></button><button className={playing==='round'?'primary':''} disabled={!!f.stop} onClick={()=>beginPlay('round')}>{playing==='round'?<Pause size={16}/>:<Play size={16}/>} {playing==='round'?'暂停播放':'自动播放本轮'}</button><button className={playing==='continuous'?'primary continuous-on':'primary'} disabled={!!f.stop} onClick={()=>beginPlay('continuous')}>{playing==='continuous'?<Pause size={16}/>:<Repeat2 size={16}/>} {playing==='continuous'?'暂停连续生成':'连续生成'}</button><select aria-label="生成播放速度" value={speed} onChange={e=>setSpeed(Number(e.target.value))}><option value={.5}>0.5×</option><option value={1}>1×</option><option value={2}>2×</option><option value={4}>4×</option></select><button aria-label="重置生成" onClick={restart}><RotateCcw size={16}/></button></div></div>
    {f.stop&&<div className="generation-complete" role="status"><ShieldCheck size={19}/>{f.stop} 可返回上一步复盘，或重置后重新生成。</div>}
    <div className="generation-stepper" aria-label="生成步骤">{generationSteps.map((s,i)=><div className={f.phase===i?'current':f.phase>i?'done':''} key={s.en}><span>{String(i+1).padStart(2,'0')}</span><b>{s.title}</b>{i<7&&<ChevronRight size={13}/>}</div>)}</div>
    <div className="gen-studio"><section className="gen-stage workspace"><div className="canvas-header"><div className="stage-title"><span className="stage-number">{String(f.phase+1).padStart(2,'0')}</span><div><h2>{lesson.title}</h2><span>{lesson.en}</span></div></div><span className="pill">{f.phase===0?'CAUSAL':f.phase<2?'[1, 8]':'[1, 24]'}</span></div><div className="generation-stage-content" key={`${session.cursor}-${session.cacheEnabled}`}>
      {f.phase===0&&<><div className="decoder-route">{['Embedding + PE','Masked Attention','Add & Norm','FFN','Add & Norm','输出 H'].map((t,i)=><span key={t+i}>{t}{i<5&&<ArrowRight size={12}/>}</span>)}</div><div className="gen-head-switch"><span>重点：最后一个 token 对前文的注意力</span>{[0,1].map(h=><button key={h} aria-pressed={head===h} className={head===h?'selected':''} onClick={()=>{stop();setHead(h);}}>Head {h+1}</button>)}</div><CausalAttention result={result} head={head}/></>}
      {f.phase===1&&<div className="hidden-states"><p>输出表示 H 的最后一行，被送入 LM Head。</p>{result.hidden.map((values,i)=><div className={i===result.tokens.length-1?'last-hidden':'other-hidden'} key={i}><span>{result.tokens[i]}<small>#{i}</small></span><Vector values={values}/><code>[1, 8]</code>{i===result.tokens.length-1&&<b>h_last →</b>}</div>)}<div className="hidden-values">{result.lastHidden.map((v,i)=><span key={i}><small>d{i+1}</small>{v.toFixed(3)}</span>)}</div></div>}
      {f.phase===2&&<div className="lm-head-scene"><div className="lm-projection"><div><b>h_last</b><Vector values={result.lastHidden}/><small>1 × 8</small></div><span>×</span><div className="lm-weight-matrix"><b>W_vocab</b><div>{result.lmWeights.map((row,i)=><div key={i}>{row.map((v,j)=><i key={j} title={`W[${i}, ${VOCAB[j]}] = ${v.toFixed(4)}`} style={{background:v<0?'#d9a68f':'#778ed3',opacity:.15+Math.abs(v)}}/>)}</div>)}</div><small>8 × 24 · 每列对应一个词</small></div><ArrowRight/><div><b>logits</b><Vector values={result.logits.slice(0,8)}/><small>1 × 24（示意前 8 项）</small></div></div><div className="projection-example"><b>以候选“{candidates[0].token}”为例</b><p>Σ h_last[d] × W[d, {candidates[0].id}] + b = <code>{candidates[0].logit.toFixed(4)}</code></p><small>使用固定权重矩阵；EOS 偏置为 −1.7，其他偏置为 0。</small></div></div>}
      {(f.phase===3||f.phase===4)&&<div className="vocab-chart"><div className="gen-caption"><span>{f.phase===3?'24 个词表项的原始 logits':'完整 Softmax 概率 · 按概率排序'}</span><span>{f.phase===3?'← 负分数 | 正分数 →':`总和 ${candidates.reduce((s,c)=>s+c.prob,0).toFixed(4)}`}</span></div>{candidates.map(c=><div className="vocab-row" key={c.id}><span>{c.token}</span><div className={f.phase===3?'logit-bar':'prob-bar'}>{f.phase===3?<i style={{width:`${Math.abs(c.logit)/maxLogit*50}%`,left:c.logit>=0?'50%':`${50-Math.abs(c.logit)/maxLogit*50}%`,background:c.logit<0?'#d6a18a':'#7c8fde'}}/>:<i style={{width:`${c.prob*100}%`}}/>}</div><code>{f.phase===3?c.logit.toFixed(3):`${(c.prob*100).toFixed(2)}%`}</code></div>)}</div>}
      {f.phase===5&&<div className="candidate-table"><div className="candidate-summary"><b>{candidates.filter(c=>c.kept).length} 个候选保留</b><span>保留概率质量 {(candidates.filter(c=>c.kept).reduce((s,c)=>s+c.prob,0)*100).toFixed(2)}% → 归一化为 100%</span></div><table><thead><tr><th>排名 / token</th><th>原概率</th><th>采样概率</th><th>筛选</th></tr></thead><tbody>{candidates.map((c,i)=><tr key={c.id} className={c.kept?'kept':'excluded'}><td><small>{String(i+1).padStart(2,'0')}</small> {c.token}</td><td>{(c.prob*100).toFixed(2)}%</td><td>{(c.samplingProbability*100).toFixed(2)}%</td><td>{c.kept?'保留':'移除'}</td></tr>)}</tbody></table></div>}
      {f.phase===6&&f.selection&&<div className="sample-scene"><span className="gen-overline">NEXT TOKEN SELECTED</span><div className="selected-token">{f.selection.token}</div><div className="sample-metrics"><span>采样概率 <b>{(f.selection.probability*100).toFixed(2)}%</b></span><span>策略 <b>{session.sampling.method}</b></span></div><div className="probability-ribbon">{candidates.filter(c=>c.kept).map(c=><span key={c.id} title={`${c.token} ${(c.samplingProbability*100).toFixed(2)}%`} className={c.id===f.selection?.id?'chosen':''} style={{flex:c.samplingProbability}}/>)}<i style={{left:`${f.selection.draw*100}%`}}/></div><p>{session.sampling.method==='greedy'?'直接选择最大 logit；此时只有一个候选。':`固定种子抽样 u = ${f.selection.draw.toFixed(4)}，落入候选的累计概率区间。`}</p><small>下一步才会把这个 token 追加到上下文。</small></div>}
      {f.phase===7&&<div className="append-scene"><div className="append-circle"><Repeat2 size={35}/></div><h3>“{f.selection?.token}”已追加</h3><div className="context-tokens">{visibleContext.map((t,i)=><span key={i} className={i===visibleContext.length-1?'generated last':''}>{t}</span>)}</div><p>{f.stop||'上下文增加一个 token。下一轮将它作为新 Query，继续预测。'}</p><div className="append-cache-note"><Database size={16}/>{session.cacheEnabled?`当前 cache 含 ${result.tokens.length} 个位置；新 token 将在下一轮写入。`:'无缓存：下一轮会重新计算整个上下文。'}</div></div>}
    </div><div className="progress-track"><span style={{width:`${(f.phase+1)/8*100}%`}}/></div></section><aside className="inspector"><div className="inspector-label"><span>理解生成这一步</span><span>{f.phase+1} / 8</span></div><div className="explanation"><h2>{lesson.title}</h2><p>{lesson.description}</p><div className="detail-label">核心公式</div><pre className="gen-formula">{lesson.formula}</pre><div className="insight"><div><b>教学提示</b><p>{lesson.tip}</p></div></div><div className="gen-round-info"><span>当前轮次 <b>{round}</b></span><span>Decoder 输入 <b>{result.tokens.length} tokens</b></span><span>最后一个位置 <b>#{result.tokens.length-1}</b></span><span>词表大小 <b>{VOCAB.length}</b></span></div></div></aside></div>
    <div className="generation-bottom"><Mask result={result} head={head}/><CachePanel session={session} result={result}/></div>
    <details className="generation-notes"><summary>这个演示与真实 LLM 有哪些区别？</summary><p>这里是固定随机权重的单层因果 Decoder，8 维 hidden state、2 个头、24 项词表。计算、因果遮罩、采样和 KV 复用都真实执行，但没有训练，不能用生成文本判断语言能力。沿用教学用正弦位置编码、Post-LN 和 ReLU；现代 LLM 的层结构可能不同。</p><p>缓存只适用于固定模型、位置和不变的历史前缀；修改提示或采样设置会开始新实验。为复盘保留的历史 hidden state / 注意力行属于页面记录，不是运行时必需的 KV Cache。</p><p>温度先作用于 logits，之后 Softmax，再执行 top-k / top-p 过滤与归一化。此演示将 top-k、top-p 作为互斥教学模式；固定种子让后退与缓存对照可复现。</p><a href="https://huggingface.co/docs/transformers/main/en/generation_strategies" target="_blank" rel="noreferrer">生成策略参考 ↗</a><a href="https://huggingface.co/docs/transformers/main/en/kv_cache" target="_blank" rel="noreferrer">KV Cache 参考 ↗</a></details>
    <footer className="page-footer"><span>未训练的教学模型 · 浏览器内计算 · 原始 Encoder 流程保持独立</span><a href="/">返回 Transformer 层内流程 →</a></footer><span className="sr-only" role="status">第 {round} 轮，第 {f.phase+1} 步：{lesson.title}</span>
  </main></div>;
}


