"use client";
import {useEffect,useMemo,useReducer,useState} from 'react';
import {Layers3,FlaskConical,Play,Pause,RotateCcw,CheckCircle2,Lightbulb,BookOpen,HelpCircle} from 'lucide-react';
import {Slider} from '@/components/ui/slider';
import {QUESTIONS,TRAINING,HELD_OUT,STEPS,LAST_FRAME,MEMORIZATION_FRAME,DEFAULT_QUESTION,distribution,prediction,frameMetrics,trajectory,STAGES,stageLabel,replayReducer,initialReplay,SCORE_TARGET,SCORE_OUTPUTS,digitScore,exactScore} from '@/lib/training/grokking';
import type {Question,ReplayMode} from '@/lib/training/grokking';

const stepText=(n:number)=>n>=1000000?'1,000,000':n.toLocaleString('en-US');
function LossReplayChart({frame,mode}:{frame:number;mode:ReplayMode}){
  const values=useMemo(()=>trajectory(mode),[mode]);
  const x=(step:number)=>56+Math.log10(step+1)/Math.log10(STEPS[LAST_FRAME]+1)*600;
  const y=(loss:number)=>210-loss/4*175;
  const line=(key:'training'|'validation')=>values.slice(0,frame+1).map((v,i)=>(i?'L':'M')+x(v.step)+','+y(v[key].loss)).join(' ');
  const now=values[frame];
  return <div className="grok-chart"><div className="grok-chart-legend"><span><i className="training"/>训练 loss</span><span><i className="validation"/>验证 loss · 没见过的题</span></div><svg viewBox="0 0 710 260" role="img" aria-label={`预设概率回放，当前训练 loss ${now.training.loss.toFixed(3)}，验证 loss ${now.validation.loss.toFixed(3)}。教学 step 使用对数刻度。`}>
  {[0,1,2,3,4].map(n=><g key={n}><line x1="56" x2="656" y1={y(n)} y2={y(n)} stroke="#e7ecf5"/><text x="43" y={y(n)+4} textAnchor="end">{n}</text></g>)}
  <text x="56" y="17">交叉熵 loss · 越低越好</text>
  <line x1={x(now.step)} x2={x(now.step)} y1="30" y2="210" stroke="#cbd3e6" strokeDasharray="5 5"/>
  <path d={line('training')} stroke="#596be7" strokeWidth="3" fill="none"/><path d={line('validation')} stroke="#32998b" strokeWidth="3" fill="none"/>
  <circle cx={x(now.step)} cy={y(now.training.loss)} r="5" fill="#596be7"/><circle cx={x(now.step)} cy={y(now.validation.loss)} r="5" fill="#32998b"/>
  {[0,1000,100000,1000000].map(n=><text key={n} x={x(n)} y="235" textAnchor={n===0?'start':n===1000000?'end':'middle'}>{n===0?'0':n===1000?'1千':n===100000?'10万':'100万'}</text>)}
  <text x="356" y="255" textAnchor="middle">教学 step · 对数刻度</text></svg></div>;
}
function QuestionGrid({training,frame,mode,selected,onSelect,tested}:{training:boolean;frame:number;mode:ReplayMode;selected:number;onSelect:(id:number)=>void;tested:boolean}){
  const questions=training?TRAINING:HELD_OUT;const stats=frameMetrics(frame,mode)[training?'training':'validation'];
  return <section className={training?'grok-question-panel training':'grok-question-panel validation'}><div className="grok-panel-title"><div><span>{training?'练习过的题':'没见过的新题'}</span><h3>{training?'训练集':'验证集'} <small>{questions.length} 题</small></h3></div><b>{(stats.accuracy*100).toFixed(0)}<small>% 答对</small></b></div><div className="grok-equation-grid">{questions.map(q=>{
    const correct=prediction(q,frame,mode)===q.target;const revealed=training||tested;return <button key={q.id} className={(revealed?(correct?'correct':'wrong'):'unseen')+(selected===q.id?' selected':'')} aria-pressed={selected===q.id} onClick={()=>onSelect(q.id)} aria-label={`${q.a} 加 ${q.b} 取余，${training?'训练题':'新题'}，${revealed?(correct?'答对':'答错'):'待查看'}`}><span>{q.a} + {q.b}</span><b>{revealed?prediction(q,frame,mode):'?'}</b><small>{revealed?(correct?'答对':'答错'):'考考它'}</small></button>;
  })}</div><p>loss <b>{stats.loss.toFixed(3)}</b><span>{training?'这些题参与了教学训练轨迹。':'预设未见题，用于观察泛化。'}</span></p></section>;
}
function ScoringLesson(){
  const[index,setIndex]=useState(0);const[metric,setMetric]=useState<'exact'|'digit'>('exact');
  const output=SCORE_OUTPUTS[index];const exact=exactScore(output),digit=digitScore(output);
  const values=SCORE_OUTPUTS.map(s=>({exact:exactScore(s),digit:digitScore(s)}));
  const line=(key:'exact'|'digit')=>values.map((v,i)=>(i?'L':'M')+(45+i*94)+','+(145-v[key]*110)).join(' ');
  return <section className="train-card grok-scoring"><div className="train-card-heading"><div><span className="section-label">SAME OUTPUTS, DIFFERENT METRICS</span><h2>看起来“突然会了”，也可能和评分有关</h2></div><span className="train-badge">独立评分样例</span></div><p className="train-copy">下面六个输出完全不变。切换评分方式，看看同一段进步怎样变成不同的曲线。</p><div className="train-choice-row" role="group" aria-label="评分方式"><button aria-pressed={metric==='exact'} className={metric==='exact'?'selected':''} onClick={()=>setMetric('exact')}>十位全对才得分</button><button aria-pressed={metric==='digit'} className={metric==='digit'?'selected':''} onClick={()=>setMetric('digit')}>按正确数字比例评分</button></div><div className="grok-score-grid"><div><span>目标答案</span><code>{SCORE_TARGET}</code><span>存档 {index+1} 的输出</span><div className="grok-digits">{Array.from(output).map((char,i)=><b key={i} className={char===SCORE_TARGET[i]?'correct':'wrong'}>{char}</b>)}</div><div className="grok-score-result"><b>{((metric==='exact'?exact:digit)*100).toFixed(0)}%</b><p>{metric==='exact'?(exact?'十位全对，终于得到 1 分。':'还有数字不对，所以整题仍然是 0 分。'):`已经有 ${Math.round(digit*10)} / 10 位数字正确。`}</p></div></div><div><svg viewBox="0 0 565 185" role="img" aria-label="全对评分在最后一个样例从零变为一，逐位评分在前面的样例已逐渐提升"><line x1="45" x2="515" y1="145" y2="145" stroke="#e0e6f2"/><line x1="45" x2="515" y1="35" y2="35" stroke="#e0e6f2"/><text x="30" y="149" textAnchor="end">0%</text><text x="30" y="39" textAnchor="end">100%</text><path d={line('exact')} fill="none" stroke="#596be7" strokeWidth={metric==='exact'?3:1.5} opacity={metric==='exact'?1:.35}/><path d={line('digit')} fill="none" stroke="#32998b" strokeWidth={metric==='digit'?3:1.5} opacity={metric==='digit'?1:.35}/><circle cx={45+index*94} cy={145-(metric==='exact'?exact:digit)*110} r="5" fill={metric==='exact'?'#596be7':'#32998b'}/>{values.map((_,i)=><text key={i} x={45+i*94} y="171" textAnchor="middle">存档{i+1}</text>)}</svg><div className="grok-chart-legend"><span><i className="training"/>全对才得分</span><span><i className="validation"/>逐位评分</span></div></div></div><label className="grok-slider-label" id="scoring-label">切换同一组输出的存档 <b>{index+1} / 6</b></label><Slider className="grok-slider" aria-labelledby="scoring-label" min={0} max={5} step={1} value={[index]} onValueChange={v=>setIndex(v[0])}/><p className="grok-footnote">这个样例演示的是评分门槛，和上方的泛化回放不同。它不证明所有能力涌现都来自评分方式。</p></section>;
}
export default function GrokkingLab(){
  const[state,dispatch]=useReducer(replayReducer,initialReplay);const[selected,setSelected]=useState(DEFAULT_QUESTION.id);const[speed,setSpeed]=useState(1);const[compare,setCompare]=useState(false);
  const q=QUESTIONS[selected];const p=distribution(q,state.frame,state.mode);const predicted=prediction(q,state.frame,state.mode);const current=frameMetrics(state.frame,state.mode);const currentGeneral=frameMetrics(state.frame,'generalize'),currentMemory=frameMetrics(state.frame,'memorize');
  const questionRevealed=q.training||state.tested;
  const atGate=state.frame>=MEMORIZATION_FRAME&&!state.tested;const startedGeneralizing=state.mode==='generalize'&&state.frame>=18;const complete=state.frame===LAST_FRAME;
  useEffect(()=>{if(!state.playing)return;const timer=setTimeout(()=>dispatch({type:'tick'}),850/speed);return()=>clearTimeout(timer);},[state.playing,state.frame,speed]);
  const chooseQuestion=(id:number)=>{setSelected(id);if(state.playing)dispatch({type:'toggle'});};
  const testQuestion=()=>{if(q.training)setSelected(DEFAULT_QUESTION.id);dispatch({type:'test'});};
  const reset=()=>{dispatch({type:'reset'});setSelected(DEFAULT_QUESTION.id);setCompare(false);};
  const testMessage=!state.tested?'训练题答对，不代表这道新题也会。':predicted===q.target?'这道题现在答对了。拖回较早存档，比较同一个问题的变化。':'这道题依然答错。练习题的低 loss，还没有带来这道新题的泛化。';
  return <div className="lab training-lab grok-lab"><header className="topbar"><a className="brand" href="/"><span className="brand-icon"><Layers3 size={23}/></span>Transformer <span className="brand-light">Lab</span></a><nav className="mode-nav" aria-label="学习模式"><a href="/">Transformer 层内流程</a><a href="/generation">LLM 生成模式</a><a href="/training" aria-current="page">模型训练实验室</a><a href="/build-model">从零造模</a></nav><span className="training-header-mark"><FlaskConical size={18}/> GROKKING</span></header><aside className="sidebar training-sidebar grok-sidebar"><div className="section-label">进一步探索</div><h3>泛化与“突然变好”</h3><a className="grok-back" href="/training">返回模型训练主线</a><nav aria-label="本页实验区域">{[['#grok-experiment','01','回放训练轨迹','Training vs Validation'],['#grok-question','02','考同一道新题','Same Question'],['#grok-contrast','03','只背答案的对照','Memorization'],['#grok-scoring','04','换一种评分方式','Metric Threshold']].map(([href,num,title,en])=><a href={href} key={href}><span className="step-number">{num}</span><div>{title}<small>{en}</small></div></a>)}</nav><div className="training-sidebar-note"><Lightbulb size={20}/><b>盯住新题的表现</b><p>Grokking 的关键，是训练集拟合之后较晚发生的泛化改善。</p><span>预设概率轨迹 · 教学回放</span></div></aside>
  <main className="main training-main grok-main"><div className="page-heading"><div><div className="eyebrow">GENERALIZATION EXPLORER</div><h1>背下答案，<span>还是学会规律？</span></h1><p className="intro">训练题先满分，新题却不会。继续回放，看两种表现何时一起变好。</p></div></div><div className="grok-method-note"><FlaskConical size={17}/><p>教学回放：预设各存档的预测概率，再统一计算 loss 与答题结果。没有在此训练神经网络，step 是教学刻度。</p></div>
  <section id="grok-experiment" className="train-card grok-experiment"><div className="train-card-heading"><div><span className="section-label">ONE TASK, TWO SETS</span><h2>任务：两个数相加，再除以 7 取余数</h2></div><span className="train-badge">49 题 · 固定划分</span></div><p className="grok-task-example">例如：5 + 6 = 11，除以 7 的余数是 <b>4</b>。<span>21 道训练题，28 道验证题；回放中保持同一组划分。</span></p>
  <div className="grok-control-bar"><div className="grok-controls"><button className="primary" onClick={()=>atGate?testQuestion():dispatch({type:'toggle'})}>{atGate?<HelpCircle size={16}/>:state.playing?<Pause size={16}/>:<Play size={16}/>} {atGate?'考一道没见过的题':state.playing?'暂停回放':complete?'重新播放':state.frame===0?'开始训练回放':'继续训练回放'}</button><button disabled={state.playing||atGate||complete} onClick={()=>dispatch({type:'scrub',frame:state.frame+1})}>下一存档</button><button onClick={reset} aria-label="重置泛化实验"><RotateCcw size={16}/>重置</button></div><label className="train-speed"><span>回放速度</span><select aria-label="回放速度" value={speed} onChange={e=>setSpeed(Number(e.target.value))}><option value=".5">慢</option><option value="1">正常</option><option value="2">快</option></select></label></div>
  <div className={startedGeneralizing?'grok-status generalizing':'grok-status'} role="status"><span className="grok-stage-number">存档 {state.frame+1} / {STEPS.length}</span><div><b>{stageLabel(state.frame,state.mode)}</b><p>{atGate?'练习题已接近满分。先考一道新题，再决定是否继续。':state.mode==='memorize'?'这条对照轨迹只记住训练题；继续回放也不会掌握新题。':state.frame<6?'先让模型拟合训练材料，观察两组表现。':state.frame<18?'训练 loss 很低，但新题还没有明显改善。':state.frame<23?'验证 loss 开始明显下降，新题逐渐答对。':'这组未见过的题也能答对了。此结果只说明本教学任务的泛化。'}</p></div><span className="grok-step">Step {stepText(STEPS[state.frame])}</span></div>
  <div className="grok-loss-layout"><LossReplayChart frame={state.frame} mode={state.mode}/><div className="grok-metrics"><div className="training"><span>训练题</span><b>{(current.training.accuracy*100).toFixed(0)}<small>% 答对</small></b><p>loss <code>{current.training.loss.toFixed(3)}</code></p></div><div className="validation"><span>没见过的新题</span><b>{(current.validation.accuracy*100).toFixed(0)}<small>% 答对</small></b><p>loss <code>{current.validation.loss.toFixed(3)}</code></p></div></div></div>
  <label className="grok-slider-label" id="grok-timeline-label">拖动存档，比较前后 <b>Step {stepText(STEPS[state.frame])}</b></label><Slider className="grok-slider" aria-labelledby="grok-timeline-label" min={0} max={LAST_FRAME} step={1} value={[state.frame]} onValueChange={v=>dispatch({type:'scrub',frame:v[0]})}/><div className="grok-checkpoints">{STAGES.map(stage=><button key={stage.frame} className={state.frame===stage.frame?'selected':''} aria-pressed={state.frame===stage.frame} onClick={()=>dispatch({type:'scrub',frame:stage.frame})}><span>{stage.label}</span><small>{stepText(STEPS[stage.frame])} step</small></button>)}</div><p className="grok-footnote">存档之间的教学时间间隔不相同，曲线横轴为对数刻度。切换存档不会重新计算或改变任何题目的划分。</p></section>
  <div className="grok-question-boards"><QuestionGrid training frame={state.frame} mode={state.mode} selected={selected} onSelect={chooseQuestion} tested={state.tested}/><QuestionGrid training={false} frame={state.frame} mode={state.mode} selected={selected} onSelect={chooseQuestion} tested={state.tested}/></div>
  <section id="grok-question" className="train-card grok-question"><div className="train-card-heading"><div><span className="section-label">TRACK THE SAME QUESTION</span><h2>固定一道题，看它什么时候答对</h2></div><span className={q.training?'train-badge':'train-badge actual'}>{q.training?'训练题 · 已练习':'验证题 · 未见过'}</span></div><p className="train-copy">点击上方题目，或使用下面的预设新题；拖动存档时，题目保持不变。</p><div className="train-choice-row">{HELD_OUT.filter(q=>[DEFAULT_QUESTION.id,2,18,32].includes(q.id)).map(question=><button key={question.id} aria-pressed={selected===question.id} className={selected===question.id?'selected':''} onClick={()=>chooseQuestion(question.id)}>{question.a} + {question.b} 取余</button>)}</div><div className="grok-question-layout"><div><div className="grok-question-equation"><span>({q.a} + {q.b}) mod 7 =</span><output className={questionRevealed?(predicted===q.target?'correct':'wrong'):''}>{questionRevealed?predicted:'?'}</output></div><div className="train-actions"><button className="primary" onClick={()=>dispatch({type:'test'})}>{questionRevealed?'重新检查这个存档':'查看模型回答'}</button><button disabled={q.id===DEFAULT_QUESTION.id} onClick={()=>chooseQuestion(DEFAULT_QUESTION.id)}>回到默认新题</button></div>{questionRevealed&&<p className="grok-answer">正确余数：<b>{q.target}</b> · 模型给它的概率：<b>{(p[q.target]*100).toFixed(1)}%</b></p>}<p className={questionRevealed&&predicted===q.target?'grok-question-feedback correct':'grok-question-feedback'}>{q.training?'这道题来自训练集。考新题才能检查泛化。':testMessage}</p></div><div className="grok-answer-probs"><span>候选余数的概率 · 当前教学存档</span>{p.map((value,i)=><div key={i} className={questionRevealed&&i===q.target?'target':''}><b>{i}</b><div><i style={{width:value*100+'%'}}/></div><code>{(value*100).toFixed(1)}%</code>{questionRevealed&&i===q.target&&<small>正确答案</small>}</div>)}</div></div>
  {compare&&<div className="grok-same-question-history">{STAGES.map(stage=><button key={stage.frame} className={state.frame===stage.frame?'selected':''} onClick={()=>dispatch({type:'scrub',frame:stage.frame})}><span>{stage.label}</span><b>{prediction(q,stage.frame,state.mode)} <small>{prediction(q,stage.frame,state.mode)===q.target?'答对':'答错'}</small></b><code>p(正确) {(distribution(q,stage.frame,state.mode)[q.target]*100).toFixed(1)}%</code></button>)}</div>}<button className="train-text-button" aria-expanded={compare} onClick={()=>setCompare(v=>!v)}>{compare?'收起同题存档':'同屏比较这道题的六个存档'}</button></section>
  <section id="grok-contrast" className="train-card grok-contrast"><div className="train-card-heading"><div><span className="section-label">A CONTROL EXPERIMENT</span><h2>训练题满分，也可能只是背下了答案</h2></div><span className="train-badge">同一题目 · 同一存档</span></div><p className="train-copy">切换轨迹，进度和当前题目保持不变。观察训练表现相近时，新题表现可以有多不同。</p><div className="train-choice-row" role="group" aria-label="泛化与记忆轨迹"><button aria-pressed={state.mode==='generalize'} className={state.mode==='generalize'?'selected':''} onClick={()=>dispatch({type:'mode',mode:'generalize'})}>较晚学到规律的轨迹</button><button aria-pressed={state.mode==='memorize'} className={state.mode==='memorize'?'selected':''} onClick={()=>dispatch({type:'mode',mode:'memorize'})}>只背训练答案的轨迹</button></div><div className="grok-contrast-grid">{[{mode:'generalize',label:'较晚泛化',stats:currentGeneral},{mode:'memorize',label:'只背答案',stats:currentMemory}].map(item=><div key={item.mode} className={state.mode===item.mode?'active':''}><h3>{item.label}</h3><p>训练题 <b>{(item.stats.training.accuracy*100).toFixed(0)}%</b> 答对</p><p>新题 <b>{(item.stats.validation.accuracy*100).toFixed(0)}%</b> 答对</p><small>新题 loss {item.stats.validation.loss.toFixed(3)}</small></div>)}</div><div className="train-small-note"><Lightbulb size={18}/><p>{state.frame<18?'现在两条轨迹可能看起来相近。拖到较晚存档，比较新题结果。':'两条轨迹都能把训练题做好，但只有泛化轨迹改善了新题。实际训练是否发生 grokking，取决于任务、模型与训练设置。'}</p></div></section>
  <div id="grok-scoring"><ScoringLesson/></div>
  <section className="grok-conclusion"><CheckCircle2 size={24}/><div><h2>观察的是某项任务的泛化改善</h2><p>训练 loss 很低，只说明训练题做得好。Grokking 关注的是拟合训练集之后，未见数据上较晚出现的明显改善；它不等于整个模型在某一刻“诞生智能”。</p></div></section>
  <details className="train-card train-details grok-explanation"><summary>这个回放怎样计算？</summary><p>每道题的目标余数由算术规则给出；训练集与验证集固定划分。两条轨迹预设目标余数的概率怎样随存档变化，其余概率保持归一化。</p><p>loss 使用 −ln(正确余数的概率)，准确率根据概率最大的候选是否正确计算。因此曲线、概率条、答题方格和存档比较始终对应同一组数据。这里没有用 SGD 训练网络，不是原论文的实验复现。</p><p>回放刻意展示训练集先拟合、验证表现较晚改善的现象，不代表所有真实模型都会按这个时间表进步。</p><a href="https://arxiv.org/abs/2201.02177" target="_blank" rel="noreferrer">Grokking 原始研究</a><a href="https://arxiv.org/abs/2304.15004" target="_blank" rel="noreferrer">涌现与评分方式研究</a></details><div className="grok-return"><a href="/training"><BookOpen size={18}/>回到模型训练主线</a><a href="/generation">继续看固定权重怎样生成文字</a></div><footer className="page-footer"><span>预设教学回放 · 数值指标统一计算 · 页面刷新后重置</span><span>Transformer Lab / Generalization</span></footer><span className="sr-only" role="status" aria-live="polite">存档 {state.frame+1}，训练题答对 {(current.training.accuracy*100).toFixed(0)}%，验证题答对 {(current.validation.accuracy*100).toFixed(0)}%。</span></main></div>;
}

