"use client";
import {useEffect,useMemo,useRef,useState} from 'react';
import {Layers3,Terminal,Check,Play,Pause,RotateCcw,Download,Upload,ChevronRight,ChevronLeft,FlaskConical} from 'lucide-react';
import {DEFAULT_CONFIG,dataset,createExperiment,trainingTarget,prediction,targetLoss,gradients,trainSteps,measure,evaluate,samples,saveCheckpoint,restoreCheckpoint,sftSettings,pretrainingCheckpoint,startSFT,generateText,learnPreferences,preferenceSummary,runTest,exportExperiment,importExperiment,type Config,type Experiment,type Metrics} from '@/lib/journey/engine';
import {PACKS,GOALS,DIALOGUES,buildTokenizer,tokenize,assistantSamples,type PackId} from '@/lib/journey/data';
import {parameterGroups} from '@/lib/training/transformer';
import {QUESTIONS,FEATURE_LABELS,REFERENCE} from '@/lib/training/engine';
import JourneyCode,{sources,downloadText} from './journey-code';
import JourneyDiagnostics from './journey-diagnostics';

const stages=[
  {title:'建立项目',en:'Project',section:'config',goal:'先决定，你要培养怎样的模型',code:'配置是传给程序的参数；源码里显示默认值。'},
  {title:'挑选语料',en:'Data',section:'samples',goal:'模型只能从你提供的材料里学习',code:'每段材料会变成多个「前缀 → 下一个 token」样本。'},
  {title:'清洗材料',en:'Clean',section:'clean',goal:'重复、空白和乱码，也会进入训练',code:'清洗函数实际过滤材料；你的选择改变后续训练集。'},
  {title:'划分数据',en:'Split',section:'split',goal:'留一些模型从未训练过的材料',code:'按整句划分；同一句的重复版本不会跨到另一个集合。'},
  {title:'制作分词器',en:'Tokenizer',section:'tokenizer',goal:'把文字转换成模型能读取的编号',code:'字符表固定；双字合并只根据训练材料的频次决定。'},
  {title:'搭建模型',en:'Model',section:'model',goal:'亲手建立一个随机初始化的 Transformer',code:'参数组定义字符、位置、注意力、前馈网络和输出投影。'},
  {title:'运行预训练',en:'Pretrain',section:'train',goal:'先走一遍，再让训练循环重复运行',code:'循环真实计算梯度并调用 Adam，没有预设 loss 曲线。'},
  {title:'检查与改进',en:'Diagnose',section:'diagnose',goal:'训练题答得好，新题也一样吗？',code:'验证集只做前向计算，不提供参数更新的梯度。'},
  {title:'监督微调',en:'SFT',section:'replay',goal:'继续训练同一个模型，让它模仿回答',code:'问答样本只训练回答；按所选比例混入原预训练文本。'},
  {title:'学习偏好',en:'Preferences',section:'preferences',goal:'体验人的选择怎样影响回答倾向',code:'这里另加有限候选策略，实际学习偏好；不更新 Transformer。'},
  {title:'最终验收',en:'Test',section:'evaluate',goal:'现在才打开留出测试集的成绩',code:'测试读取最终权重；成绩不参加训练或调参。'},
  {title:'获得你的模型',en:'Archive',section:'archive',goal:'把权重、配置和实验记录一起带走',code:'导出实验文件，重新导入后可以恢复同一组权重。'},
];
function ProgressChart({experiment}:{experiment:Experiment}){
  const points=experiment.history;const max=Math.max(1,...points.flatMap(p=>[p.train,p.validation]))*1.1,last=Math.max(40,experiment.model.step);const x=(n:number)=>48+n/last*500,y=(n:number)=>170-n/max*140;
  return <div className="journey-chart"><svg viewBox="0 0 590 210" role="img" aria-label="实际训练与验证损失曲线"><text x="6" y="18">loss</text>{[0,.5,1].map(n=><g key={n}><line x1="48" x2="548" y1={y(max*n)} y2={y(max*n)} stroke="#e5eaf5"/><text x="40" y={y(max*n)+4} textAnchor="end">{(max*n).toFixed(1)}</text></g>)}{(['train','validation'] as const).map(key=><g key={key}><path d={points.map((p,i)=>`${i?'L':'M'}${x(p.step)},${y(p[key])}`).join(' ')} stroke={key==='train'?'#596be7':'#d9974c'} strokeWidth="2.5" fill="none"/>{points.length===1&&<circle cx={x(points[0].step)} cy={y(points[0][key])} r="4" fill={key==='train'?'#596be7':'#d9974c'}/>}</g>)}<text x="48" y="198">0</text><text x="548" y="198" textAnchor="end">{last} step</text></svg><div><span><i/>训练 loss</span><span><i/>验证 loss</span><small>每 40 步与手动操作后实际评测；SFT 继续同一条曲线</small></div></div>;
}
function MetricRow({train,validation}:{train:Metrics;validation:Metrics}){return <div className="journey-metrics"><div><span>训练 loss</span><b>{train.loss.toFixed(3)}</b><small>下一个 token 命中 {(train.accuracy*100).toFixed(1)}%</small></div><div><span>验证 loss</span><b>{validation.loss.toFixed(3)}</b><small>下一个 token 命中 {(validation.accuracy*100).toFixed(1)}%</small></div></div>;}
function TokenRow({text,tokenizer}:{text:string;tokenizer:ReturnType<typeof buildTokenizer>}){return <div className="journey-tokens">{tokenize(text,tokenizer).map((t,i)=><span key={i}>{t.token}<small>#{t.id}{t.id===0?' · 未知':''}</small></span>)}</div>;}
function ActualOutput({experiment,prefix,model,assistant=false}:{experiment:Experiment;prefix:string;model?:Experiment['model'];assistant?:boolean}){const output=useMemo(()=>generateText(experiment,prefix,model),[experiment,prefix,model]);return <div className="journey-output"><span>真实 Transformer {assistant?'回答':'续写'} · 贪心选择</span><output>{assistant?output.text.slice(prefix.length):output.text}</output><div>{output.steps.map((t,i)=><span key={i}>{t.token}<small>{(t.probability*100).toFixed(1)}%</small></span>)}</div><p>每步取概率最大的 token，接回上下文；生成时权重固定。出现混搭或乱码，是这个小模型实际算出的结果。</p></div>;}

export default function ModelJourney(){
  const [stage,setStage]=useState(0),[completed,setCompleted]=useState<number[]>([]),[draft,setDraft]=useState<Config>(()=>structuredClone(DEFAULT_CONFIG));
  const [experiment,setExperiment]=useState<Experiment|null>(null),[previous,setPrevious]=useState<Experiment|null>(null);
  const [consoleLines,setConsoleLines]=useState<string[]>([]),[notice,setNotice]=useState(''),[error,setError]=useState('');
  const [automatic,setAutomatic]=useState(false),[speed,setSpeed]=useState(1),[manual,setManual]=useState(0),[manualBefore,setManualBefore]=useState<Experiment|null>(null),[manualP,setManualP]=useState<number[]|null>(null),[manualG,setManualG]=useState<number[]|null>(null);
  const [checkpoint,setCheckpoint]=useState<number|null>(null),[dialogue,setDialogue]=useState(0),[question,setQuestion]=useState(0),[pair,setPair]=useState(1),[prompt,setPrompt]=useState('');
  const importRef=useRef<HTMLInputElement>(null);
  const [testMode,setTestMode]=useState<'assistant'|'completion'>('assistant');
  const current=stages[stage];const config=experiment?.config??draft;const locked=!!experiment;
  const data=useMemo(()=>dataset(config),[config]);const tokenizer=useMemo(()=>experiment?.tokenizer??buildTokenizer(data.train,config.tokenizer),[experiment?.tokenizer,data.train,config.tokenizer]);
  const modelGroups=useMemo(()=>parameterGroups(tokenizer.vocab.length,config.width,config.context),[tokenizer.vocab.length,config.width,config.context]);
  const stats=useMemo(()=>experiment?{train:evaluate(experiment.model,samples(experiment,'train'),tokenizer.vocab.length),validation:evaluate(experiment.model,samples(experiment,'validation'),tokenizer.vocab.length)}:null,[experiment,tokenizer.vocab.length]);
  const focused=experiment?.checkpoints.find(cp=>cp.id===checkpoint)?.model??experiment?.model;
  const goal=GOALS.find(g=>g.id===config.goal)!;const actualPrompt=prompt||goal.prompt;
  const record=(line:string)=>setConsoleLines(lines=>[...lines,line].slice(-40));
  const stop=()=>{setAutomatic(false);setManual(0);setManualBefore(null);setManualP(null);setManualG(null);};
  const go=(n:number)=>{stop();setCheckpoint(null);setNotice('');setError('');setStage(n);};
  const change=(patch:Partial<Config>)=>setDraft(c=>({...c,...patch}));
  const exportFile=(e:Experiment)=>downloadText(exportExperiment(e===experiment?{...e,logs:[...new Set([...e.logs,...consoleLines])].slice(-80)}:e,sources),`${e.config.name.replace(/[^a-zA-Z0-9\u4e00-\u9fa5_-]/g,'-')||'model'}-tiny-model.json`,'application/json');
  const initialise=()=>{try{const e=createExperiment(draft);setExperiment({...e,logs:[...consoleLines,...e.logs].slice(-80)});setCompleted(c=>Array.from(new Set([...c,0,1,2,3,4,5])));record(e.logs[0]);setNotice('模型已建立。所有前缀共用这些参数，现在可以开始训练。');setError('');}catch(err){setError((err as Error).message);}};
  const batch=(count:number)=>{
    if(!experiment)return;
    const began=performance.now();let next=measure(trainSteps(experiment,count));const point=next.history.at(-1)!;
    const line=`${next.phase==='sft'?'SFT':'预训练'} Step ${next.model.step}：训练 loss ${point.train.toFixed(3)}，验证 loss ${point.validation.toFixed(3)}；本批 ${(performance.now()-began).toFixed(0)} ms。`;
    next={...next,logs:[...next.logs,line].slice(-80)};setExperiment(next);record(line);
  };
  useEffect(()=>{if(!automatic||!experiment||![6,8].includes(stage))return;const done=experiment.phase==='sft'?experiment.sftSteps:experiment.pretrainSteps,limit=experiment.phase==='sft'?800:experiment.config.budget;if(done>=limit){setAutomatic(false);return;}const timer=setTimeout(()=>batch(40),360/speed);return()=>clearTimeout(timer);},[automatic,experiment,stage,speed]);
  const manualNext=()=>{
    if(!experiment||experiment.phase!=='pretrain')return;
    const before=manualBefore??experiment,sample=trainingTarget(before);
    if(manual===0){setManualBefore(experiment);record(`取训练样本：${sample.prefix} → ${sample.answer}；测试材料未参与。`);}
    if(manual===1){const p=prediction(before,sample).probabilities;setManualP(p);record(`Transformer 前向：目标「${sample.answer}」的概率 ${(p[sample.target]*100).toFixed(2)}%。`);}
    if(manual===2){record(`交叉熵 −ln(p) = ${targetLoss(before,sample).toFixed(5)}。`);}
    if(manual===3){const g=gradients(before,sample);setManualG(g);record(`反向传播：${g.length} 个参数的梯度已计算；全局范数 ${Math.sqrt(g.reduce((s,v)=>s+v*v,0)).toFixed(5)}。`);}
    if(manual===4){const next=measure(trainSteps(experiment,1));setExperiment(next);record(`Adam 已更新；Step ${next.model.step}，本样本目标概率 ${(prediction(next,sample).probabilities[sample.target]*100).toFixed(2)}%。`);}
    if(manual===5){setManual(0);setManualBefore(null);setManualP(null);setManualG(null);return;}
    setManual(n=>n+1);
  };
  const rebuild=()=>{if(experiment)setPrevious(experiment);stop();setExperiment(null);setCompleted([0]);setDraft(structuredClone(config));setStage(1);setPrompt('');setCheckpoint(null);setConsoleLines([]);setNotice('旧实验暂时保留，可导出或恢复。重新选择材料后会建立新模型。');};
  const startFineTuning=()=>{if(!experiment)return;stop();const e=startSFT(experiment);setExperiment(e);record('继续使用当前权重进行 SFT；问题被遮住 loss，只训练回答 token。');};
  const restore=(id:number)=>{if(!experiment)return;try{stop();const e=restoreCheckpoint(experiment,id);setExperiment(e);setCheckpoint(null);setCompleted(Array.from({length:e.phase==='sft'?8:6},(_,i)=>i));setStage(e.phase==='sft'?8:6);setNotice(`已恢复 Step ${e.model.step}；先前权重已保留在检查点中。可以继续训练，再重新验收。`);setError('');record(`恢复检查点 ${id}，旧测试报告失效。`);}catch(err){setError((err as Error).message);}};
  const setSFT=(patch:Partial<ReturnType<typeof sftSettings>>)=>{if(!experiment)return;stop();const settings={...sftSettings(experiment),...patch};setExperiment({...experiment,sftSettings:settings,logs:[...experiment.logs,`微调设置：原文混入 ${settings.replay*100}%，学习率为预训练的 ${settings.rate*100}%。`].slice(-80)});setNotice('设置用于接下来的更新；已有权重没有重置。要比较两种方案，请先恢复相同的预训练检查点。');};
  const addPreference=(chosen:number)=>{if(!experiment||experiment.preferences.length>=60)return;setExperiment({...experiment,preferences:[...experiment.preferences,{question,chosen,rejected:chosen===0?pair:0}],rewardWeights:[0,0,0,0],policyLogits:QUESTIONS.map(()=>REFERENCE.map(Math.log)),preferenceUpdates:0});record(`记录偏好：问题 ${question+1}，回答 ${String.fromCharCode(65+chosen)} 优于 ${String.fromCharCode(65+(chosen===0?pair:0))}。`);setPair(p=>p===3?1:p+1);};
  const nextAllowed=stage===0?draft.name.trim().length>0:stage===1?config.packs.length>0:stage===3?data.train.length>0&&data.validation.length>0&&data.test.length>0:stage===5?!!experiment:stage===6?!!experiment&&experiment.pretrainSteps>=40:stage===8?!!experiment&&experiment.sftSteps>=40:stage===9?!!experiment&&experiment.preferenceUpdates>0:stage===10?!!experiment?.test:true;
  const next=()=>{if(!nextAllowed)return;setCompleted(c=>Array.from(new Set([...c,stage])));go(Math.min(11,stage+1));};
  const importFile=async(file:File)=>{try{stop();if(file.size>8_000_000)throw Error('文件超过 8 MB。');const e=importExperiment(await file.text());setConsoleLines([]);setExperiment(e);setDraft(structuredClone(e.config));const step=e.test?11:e.preferenceUpdates?10:e.sftSteps?8:6;setCompleted(Array.from({length:step},(_,i)=>i));setStage(step);setCheckpoint(null);setPrompt('');setNotice(`已恢复「${e.config.name}」的 Step ${e.model.step}，导入时没有重新初始化权重。`);record(`导入成功：${e.model.weights.length} 个参数，Adam 状态和记录已恢复。`);setError('');}catch(err){setError(`无法导入：${(err as Error).message}`);}finally{if(importRef.current)importRef.current.value='';}};
  const nameChange=(name:string)=>{change({name});if(experiment&&name.trim())setExperiment({...experiment,config:{...experiment.config,name}});};
  const section=stage===6&&manual>0&&manual<5?(manual===1?'forward':manual===2?'loss':manual===3?'backward':'optimizer'):current.section;
  return <div className="lab journey-lab"><header className="topbar"><a className="brand" href="/"><span className="brand-icon"><Layers3 size={23}/></span>Transformer <span className="brand-light">Lab</span></a><nav className="mode-nav" aria-label="学习模式"><a href="/">Transformer 层内流程</a><a href="/generation">LLM 生成模式</a><a href="/training">模型训练实验室</a><a href="/build-model" aria-current="page">从零造模</a></nav></header>
    <aside className="sidebar journey-sidebar"><div className="section-label">YOUR MODEL / 12 STEPS</div><h3>从空项目，到模型</h3><nav aria-label="造模步骤">{stages.map((s,i)=><button className={i===stage?'step active':completed.includes(i)?'step completed':'step'} disabled={i>stage&&!completed.includes(i)&&i>Math.max(-1,...completed)+1} aria-current={i===stage?'step':undefined} onClick={()=>go(i)} key={s.title}><span className="step-number">{completed.includes(i)?<Check size={13}/>:String(i+1).padStart(2,'0')}</span><span>{s.title}<small>{s.en}</small></span></button>)}</nav><p>实际训练微型 Transformer。完整流程用于理解大模型开发，不代表浏览器能训练商业规模的大语言模型。</p></aside>
    <main className="main journey-main"><div className="journey-heading"><div><span className="eyebrow">BUILD YOUR OWN MODEL</span><h1>从零造模</h1><p>看真实代码，整理数据，运行训练，把自己的微型模型带走。</p></div><div className="journey-file-actions"><button onClick={()=>importRef.current?.click()}><Upload size={15}/>导入实验</button>{experiment&&<button onClick={()=>exportFile(experiment)}><Download size={15}/>导出当前模型</button>}<input ref={importRef} type="file" accept=".json,application/json" className="sr-only" aria-label="导入实验 JSON 文件" onChange={e=>{const file=e.target.files?.[0];if(file)void importFile(file);}}/></div></div>
      <div className="journey-mobile-steps"><label>当前步骤<select value={stage} onChange={e=>go(Number(e.target.value))}>{stages.map((s,i)=><option key={i} value={i} disabled={i>stage&&!completed.includes(i)&&i>Math.max(-1,...completed)+1}>{String(i+1).padStart(2,'0')} {s.title}</option>)}</select></label></div>
      <div className="journey-project-strip"><div><Terminal size={18}/><b>{config.name||'未命名模型'}</b></div><span>{goal.label}</span><span>{experiment?`${experiment.model.weights.length.toLocaleString()} 参数 · Step ${experiment.model.step}`:'尚未初始化'}</span><span>{experiment?.phase==='sft'?'监督微调':experiment?'预训练':'预训练准备'}</span><div className="journey-progress" aria-label={`已完成 ${completed.length} 个环节`}><i style={{width:completed.length/12*100+'%'}}/></div></div>
      {notice&&<p className="journey-notice" role="status">{notice}</p>}{error&&<div className="journey-error" role="alert"><p>{error}</p>{!experiment&&data.train.length===0&&<button onClick={()=>go(2)}>回到第 3 步：恢复训练材料</button>}{!experiment&&(data.validation.length===0||data.test.length===0)&&<button onClick={()=>go(3)}>回到第 4 步：检查划分与保留材料</button>}</div>}
      {previous&&!experiment&&<div className="journey-backup"><span>上一份实验：「{previous.config.name}」· Step {previous.model.step}</span><button onClick={()=>exportFile(previous)}>导出备份</button><button onClick={()=>{setExperiment(previous);setDraft(structuredClone(previous.config));setStage(previous.sftSteps?8:6);setCompleted([0,1,2,3,4,5]);setPrevious(null);setNotice('已恢复之前的模型。');}}>恢复旧实验</button></div>}
      <div className="journey-step-heading"><span>{String(stage+1).padStart(2,'0')} / 12</span><div><h2>{current.goal}</h2><p>{stage<6?'先准备项目，再初始化参数。':stage===9?'此步为四候选偏好教学实验，和 Transformer 权重分开保存。':'本步骤使用你建立的模型、词表和数据。'}</p></div><a className="journey-code-link" href="#journey-source">查看本步代码</a></div>
      <div className="journey-workspace"><JourneyCode section={section} stage={stage} description={stage===6&&manual>0&&manual<5?'教学暂停：点击右侧按钮，调用对应计算；结果写入运行记录。':current.code} consoleLines={[...(experiment?.logs??[]),...consoleLines].slice(-10)}/><div className="journey-experiment">
        {locked&&stage>0&&stage<6&&<div className="journey-backup"><span>当前模型已初始化。修改语料、清洗、划分、分词或结构，需要建立新模型。</span><button onClick={()=>{rebuild();setStage(stage);setCompleted(Array.from({length:stage},(_,i)=>i));}}>保留旧实验，从这一步重新配置</button></div>}
        {stage===0&&<section className="journey-card"><div className="journey-card-title"><h3>创建你的项目</h3><span>不需要写代码</span></div><label className="journey-field">模型名字<input maxLength={40} value={draft.name} onChange={e=>nameChange(e.target.value)} placeholder="给你的模型起个名字"/></label><fieldset><legend>你想培养哪种小助手？</legend>{GOALS.map(g=><button className={config.goal===g.id?'selected':''} disabled={locked} key={g.id} aria-pressed={config.goal===g.id} onClick={()=>change({goal:g.id,packs:[g.id]})}>{g.label}</button>)}</fieldset><p>你只需选择预设材料和问题。代码窗展示实际实现；右边的配置作为参数传入程序。</p><div className="journey-callout">实际运行：浏览器中的微型 Transformer。<br/>规模说明：真实大模型会使用更多参数、更多数据和专门算力，训练流程的基本环节可以在这里体验。</div><button className="primary" disabled={!nextAllowed} onClick={()=>{record(`项目命名为「${config.name}」，目标：${goal.label}。`);next();}}>建立项目</button></section>}
        {stage===1&&<section className="journey-card"><h3>选择训练材料包</h3><p>选中的材料会进入后面的清洗和划分。没有选择的主题，模型无法从这批训练材料中学习。</p><div className="journey-packs">{PACKS.map(p=><label key={p.id}><input type="checkbox" disabled={locked} checked={config.packs.includes(p.id)} onChange={e=>change({packs:e.target.checked?[...config.packs,p.id]:config.packs.filter(id=>id!==p.id)})}/><div><b>{p.label}</b><span>{p.description}</span></div><small>8 句 + 3 条问题材料</small></label>)}</div><div className="journey-list"><b>原始材料 · {data.raw.length} 条</b>{data.raw.map(r=><div key={r.id}><span>{r.text}</span>{r.issue&&<small>{r.issue}</small>}</div>)}</div></section>}
        {stage===2&&<section className="journey-card"><h3>先处理有问题的材料</h3><fieldset><legend>清洗规则</legend>{([['trim','去掉首尾空白'],['dedupe','移除重复句子'],['garbage','移除乱码']] as const).map(([key,label])=><label className="journey-check" key={key}><input type="checkbox" disabled={locked} checked={config.cleaning[key]} onChange={e=>change({cleaning:{...config.cleaning,[key]:e.target.checked}})}/>{label}</label>)}</fieldset><div className="journey-metrics"><div><span>清洗前</span><b>{data.raw.length}</b></div><div><span>实际保留</span><b>{data.clean.length}</b></div></div><p>还可以手动排除一条材料。重复句子被保留时，会增加它在训练中的出现次数；乱码可能产生未知 token。</p><div className="journey-list">{data.raw.map(r=><label key={r.id}><input type="checkbox" disabled={locked} checked={!config.excluded.includes(r.id)} onChange={e=>change({excluded:e.target.checked?config.excluded.filter(id=>id!==r.id):[...config.excluded,r.id]})}/><span>{r.text}</span><small>{data.clean.some(c=>c.id===r.id)?'保留':'已过滤'}</small></label>)}</div><button onClick={()=>record(`清洗已执行：${data.raw.length} 条 → ${data.clean.length} 条。去空白 ${config.cleaning.trim}，去重 ${config.cleaning.dedupe}，去乱码 ${config.cleaning.garbage}。`)}>运行清洗，查看记录</button></section>}
        {stage===3&&<section className="journey-card"><h3>训练、验证与最终测试</h3><div className="journey-choice"><button className={!config.moreTraining?'selected':''} disabled={locked} onClick={()=>change({moreTraining:false})}>多留评测材料 · 5/2/1</button><button className={config.moreTraining?'selected':''} disabled={locked} onClick={()=>change({moreTraining:true})}>多给训练材料 · 6/1/1</button></div><p>比例按每包 8 条正常材料划分；清洗和排除之后，实际数量如下。同一句的所有前缀和重复版本都留在同一个集合，避免答案泄漏。</p><div className="journey-splits">{(['train','validation','test'] as const).map((key,i)=><div key={key}><b>{['训练集','验证集','测试集'][i]} · {data[key].length} 句</b><small>{['提供梯度，更新参数','观察表现，指导改进','最后验收，训练不用'][i]}</small>{data[key].map(r=><p key={r.id}>{r.text}</p>)}</div>)}</div>{!nextAllowed&&<p className="journey-error">三个集合都需要至少保留一句材料。请返回清洗页恢复一些句子。</p>}{!nextAllowed&&<button onClick={()=>go(2)}>回到第 3 步：恢复保留材料</button>}<button onClick={()=>record(`整句划分完成：训练 ${data.train.length}，验证 ${data.validation.length}，测试 ${data.test.length}；三组来源不交叉。`)}>运行数据划分</button></section>}
        {stage===4&&<section className="journey-card"><h3>选择怎样切分文字</h3><div className="journey-choice"><button disabled={locked} className={config.tokenizer==='char'?'selected':''} onClick={()=>change({tokenizer:'char'})}>按字符</button><button disabled={locked} className={config.tokenizer==='pair'?'selected':''} onClick={()=>change({tokenizer:'pair'})}>高频双字合并</button></div><p>双字合并是简化的分词实验：从训练集找出最多 8 个高频相邻字符组合，再从左到右匹配；并非完整 BPE。固定字符表是公开的符号表，不用测试答案训练参数。</p><TokenRow text={data.train[0]?.text??'小猫喜欢吃鱼。'} tokenizer={tokenizer}/><div className="journey-callout">词表：{tokenizer.vocab.length} 个 token，包括 [UNK]。<br/>实际合并：{tokenizer.merges.join('、')||'无，保持字符切分'}。</div><button onClick={()=>record(`分词器已建立：${tokenizer.vocab.length} 个 token；${tokenizer.merges.length} 个训练集双字合并。`)}>运行分词器代码</button></section>}
        {stage===5&&<section className="journey-card"><h3>定义模型与训练设置</h3><fieldset><legend>隐藏维度 · 都是实际模型配置</legend>{([8,12,16] as const).map(width=><button key={width} disabled={locked} aria-pressed={config.width===width} className={config.width===width?'selected':''} onClick={()=>change({width})}>{width} 维</button>)}</fieldset><fieldset><legend>最大上下文 token 数</legend>{([16,24] as const).map(context=><button key={context} disabled={locked} aria-pressed={config.context===context} className={config.context===context?'selected':''} onClick={()=>change({context})}>{context} token</button>)}</fieldset><label className="journey-field">学习率 · {config.lr.toFixed(3)}<input type="range" min=".001" max=".01" step=".001" value={config.lr} disabled={locked} onChange={e=>change({lr:Number(e.target.value)})}/></label><label className="journey-field">预训练上限<select disabled={locked} value={config.budget} onChange={e=>change({budget:Number(e.target.value)})}>{[400,800,1600,2400].map(n=><option key={n} value={n}>{n} 步</option>)}</select></label><div className="journey-architecture"><span>字符 + 位置 Embedding</span><span>1 层 · 1 个因果注意力头</span><span>前馈网络 {config.width} → {config.width*2} → {config.width}</span><span>词表投影 · {tokenizer.vocab.length} 个输出</span></div><div className="journey-callout">实际参数总数：<b>{modelGroups.reduce((s,g)=>s+g.size,0).toLocaleString()}</b>。改变维度和分词方式会改变真实参数量。初始化使用固定种子，可复现同一实验。</div>{!experiment?<button className="primary" onClick={initialise}>执行初始化，建立模型</button>:<p className="journey-success">模型已初始化 · Step {experiment.model.step}。重新选择结构或语料需要建立新模型。</p>}</section>}
        {stage===6&&experiment&&<section className="journey-card"><div className="journey-card-title"><h3>代码开始真正训练</h3><span>{experiment.pretrainSteps} / {config.budget} 步</span></div>{experiment.phase==='sft'&&<p className="journey-callout">模型已经进入 SFT。要继续预训练，请回到检查页恢复一个预训练检查点；更换语料需要重新建立模型。</p>}<div className="journey-manual"><b>先手动走一次训练</b><div className="journey-manual-phases">{['取样','预测','loss','梯度','Adam','复查'].map((p,i)=><span className={manual===i?'active':manual>i?'done':''} key={p}>{i+1} {p}</span>)}</div><p>当前样本：{trainingTarget(manualBefore??experiment).prefix} → <b>{trainingTarget(manualBefore??experiment).answer}</b></p>{manualP&&<p>更新前目标概率 {(manualP[trainingTarget(manualBefore??experiment).target]*100).toFixed(2)}% · loss {(-Math.log(Math.max(1e-15,manualP[trainingTarget(manualBefore??experiment).target]))).toFixed(4)}</p>}{manualG&&<div className="journey-gradient-summary">{modelGroups.filter(g=>['token','q','k','v','up','head'].includes(g.name)).map(g=><div key={g.name}><span>{g.label}</span><b>{Math.sqrt(manualG.slice(g.start,g.start+g.size).reduce((s,v)=>s+v*v,0)).toFixed(4)}</b></div>)}</div>}<button disabled={automatic||experiment.pretrainSteps>=config.budget||experiment.phase!=='pretrain'} onClick={manualNext}>{['读取一个训练样本','运行 Transformer 前向','计算交叉熵 loss','反向传播到所有参数','执行 Adam 更新','查看下一样本'][manual]}</button>{manual>0&&<button disabled={automatic} onClick={stop}>结束分步观察</button>}</div>{stats&&<MetricRow {...stats}/>}<ProgressChart experiment={experiment}/><div className="journey-actions"><button className="primary" disabled={experiment.pretrainSteps>=config.budget||experiment.phase!=='pretrain'||(manual>0&&manual<5)} onClick={()=>{setManual(0);setManualBefore(null);setManualP(null);setManualG(null);setAutomatic(v=>!v);}}>{automatic?<Pause size={15}/>:<Play size={15}/>} {automatic?'暂停':'自动训练'}</button><button disabled={automatic||experiment.pretrainSteps>=config.budget||(manual>0&&manual<5)||experiment.phase!=='pretrain'} onClick={()=>batch(40)}>运行 40 步</button><label>节奏<select value={speed} onChange={e=>setSpeed(Number(e.target.value))}><option value="1">正常</option><option value="2">快</option><option value="3">更快</option></select></label></div><p>至少运行 40 步后可进入下一环节，推荐训练到上限再比较。训练中的模型与下面生成使用同一套权重。</p><ActualOutput experiment={experiment} prefix={actualPrompt}/></section>}
        {stage===7&&experiment&&stats&&<section className="journey-card"><h3>检查泛化与存档</h3><MetricRow {...stats}/><ProgressChart experiment={experiment}/><div className="journey-callout">{stats.validation.loss>stats.train.loss+1?'验证 loss 明显高于训练 loss：训练材料学得更好，但新材料仍有困难。这个差距提示泛化不足，不能单凭它诊断原因。':stats.validation.accuracy<.5?'验证材料还有不少位置预测错误。训练曲线下降，并不等于新句子已经学会。':'验证集上已学到一些搭配。这只是少量留出句子的成绩，不代表通用智能。'}</div><div className="journey-choice">{experiment.checkpoints.map(cp=><button key={cp.id} className={checkpoint===cp.id?'selected':''} onClick={()=>setCheckpoint(cp.id)}>{cp.label}<small>Step {cp.id}</small></button>)}<button className={checkpoint===null?'selected':''} onClick={()=>setCheckpoint(null)}>当前权重</button></div><p>正在查看 Step {focused?.step}；选择检查点只预览；点击恢复才会改变当前权重。</p><ActualOutput experiment={experiment} prefix={actualPrompt} model={focused}/><div className="journey-actions">{checkpoint!==null&&<button className="primary" disabled={checkpoint===experiment.model.step} onClick={()=>restore(checkpoint)}>恢复这个检查点并继续训练</button>}<button disabled={experiment.phase!=='pretrain'||experiment.pretrainSteps>=config.budget} onClick={()=>{batch(Math.min(400,config.budget-experiment.pretrainSteps));setCheckpoint(null);}}>继续预训练，最多 400 步</button><button onClick={()=>{const e=saveCheckpoint(experiment,'手动检查');setExperiment(e);record(`保存了 Step ${e.model.step} 的完整权重和 Adam 状态。`);}}>保存检查点</button><button onClick={rebuild}>保留结果，换材料重新训练</button></div><a href="/training/grokking">进一步了解“背下答案”和“学会规律”</a></section>}
        {stage===8&&experiment&&<section className="journey-card"><div className="journey-card-title"><h3>给模型看助手回答示范</h3><span>实际 SFT · {experiment.sftSteps} / 800 步</span></div><div className="journey-choice">{DIALOGUES.map((d,i)=><button className={dialogue===i?'selected':''} key={d.question} onClick={()=>setDialogue(i)}>{d.question}</button>)}</div><div className="journey-dialogue"><div><small>提供上下文 · 不作为 loss 目标</small><p>问：{DIALOGUES[dialogue].question}答：</p></div><div><small>助手示范 · 回答 token 提供 loss 目标</small><TokenRow text={DIALOGUES[dialogue].answer} tokenizer={tokenizer}/></div></div><p>保持同一个 Transformer 的权重与 Adam 状态。三个示范题用于训练，答对它们可能只是记住回答。每 40 步暂停比较续写和未训练的改写题，再决定是否继续。混入原文和降低学习率是可尝试的修复方案，结果需实际比较。</p><fieldset><legend>微调更新中，原预训练文本占多少？</legend>{([0,.25,.5] as const).map(replay=><button key={replay} disabled={automatic} className={sftSettings(experiment).replay===replay?'selected':''} aria-pressed={sftSettings(experiment).replay===replay} onClick={()=>setSFT({replay})}>{replay===0?'只学问答':`混入 ${replay*100}% 原文`}</button>)}</fieldset><fieldset><legend>微调学习率 · 预训练学习率的比例</legend>{([.15,.35,.7] as const).map(rate=><button key={rate} disabled={automatic} className={sftSettings(experiment).rate===rate?'selected':''} aria-pressed={sftSettings(experiment).rate===rate} onClick={()=>setSFT({rate})}>{rate*100}%{rate===.15?' · 更小':rate===.35?' · 默认':''}</button>)}</fieldset><p>当前实际学习率 {(config.lr*sftSettings(experiment).rate).toFixed(5)}；每 4 次更新中 {sftSettings(experiment).replay*4} 次学习原训练文本，其余学习示范回答。混入只取原训练集，验证和测试集不参与。</p><div className="journey-actions">{experiment.phase==='pretrain'?<button className="primary" onClick={startFineTuning}>用当前权重开始 SFT</button>:<><button className="primary" disabled={experiment.sftSteps>=800} onClick={()=>setAutomatic(v=>!v)}>{automatic?<Pause size={15}/>:<Play size={15}/>} {automatic?'暂停微调':'自动微调'}</button><button disabled={automatic||experiment.sftSteps>=800} onClick={()=>batch(40)}>微调 40 步</button></>}</div><div className="journey-callout">回答位置实际平均 loss：{evaluate(experiment.model,assistantSamples(tokenizer,config.context),tokenizer.vocab.length).loss.toFixed(3)}。至少微调 40 步后可继续。</div><div className="journey-sft-compare"><div><b>进入 SFT 前的同一模型</b><ActualOutput experiment={experiment} prefix={`问：${DIALOGUES[dialogue].question}答：`} model={pretrainingCheckpoint(experiment)?.model??experiment.initial}/></div><div><b>当前模型 · Step {experiment.model.step}</b><ActualOutput experiment={experiment} prefix={`问：${DIALOGUES[dialogue].question}答：`}/></div></div></section>}
        {stage===9&&experiment&&<section className="journey-card"><h3>你更喜欢哪条回答？</h3><div className="journey-callout">四候选偏好教学实验：真实记录你的选择，训练一个线性评分器和候选概率策略。它们作为附加实验保存；本步没有执行 PPO，也没有更新 Transformer 权重。</div><div className="journey-choice">{QUESTIONS.map((q,i)=><button key={q.question} className={question===i?'selected':''} onClick={()=>{setQuestion(i);setPair(1);}}>{q.question}</button>)}</div><div className="journey-preferences">{[0,pair].map(i=><button disabled={experiment.preferences.length>=60} key={i} onClick={()=>addPreference(i)}><small>回答 {String.fromCharCode(65+i)}</small><p>{QUESTIONS[question].candidates[i].text}</p><b>更喜欢这条</b></button>)}</div><div className="journey-actions"><button onClick={()=>setPair(p=>p===3?1:p+1)}>跳过这组</button><span>已记录 {experiment.preferences.length} / 60 组</span><button disabled={!experiment.preferences.length} onClick={()=>{setExperiment({...experiment,preferences:experiment.preferences.slice(0,-1),rewardWeights:[0,0,0,0],policyLogits:QUESTIONS.map(()=>REFERENCE.map(Math.log)),preferenceUpdates:0});record('撤销最近一次标注；评分器和候选策略已重置，下次只使用剩余偏好。');}}>撤销最近标注</button></div><button className="primary" disabled={!experiment.preferences.length||experiment.preferenceUpdates>=6000} onClick={()=>{const e=learnPreferences(experiment);setExperiment(e);record(`附加评分器更新：偏好 loss ${preferenceSummary(e,question).loss.toFixed(4)}，策略更新累计 ${e.preferenceUpdates} 次。`);}}>训练评分器与候选策略 · 30 次</button><div className="journey-reward-weights">{FEATURE_LABELS.map((name,i)=><div key={name}><span>{name}</span><b>{experiment.rewardWeights[i].toFixed(3)}</b></div>)}</div><div className="journey-candidates">{QUESTIONS[question].candidates.map((c,i)=><div key={i}><span>{c.text}</span><b>{(preferenceSummary(experiment,question).probabilities[i]*100).toFixed(1)}%</b></div>)}</div><p>如果反复选择奉承回答，评分器可能提高奉承的权重，候选策略也会更常选它。概率来自实际计算，结果由你的选择决定。</p><button onClick={()=>{setExperiment({...experiment,logs:[...experiment.logs,'用户跳过附加偏好教学。'].slice(-80)});setCompleted(c=>[...new Set([...c,9])]);go(10);}}>跳过偏好教学，直接验收模型</button></section>}
        {stage===10&&experiment&&stats&&<section className="journey-card"><h3>留出测试集，最后才计分</h3><p>这 {data.test.length} 句材料没有给预训练或 SFT 提供梯度。报告评测每个位置的下一个 token，准确率不是问答质量或智能分数。</p><MetricRow {...stats}/>{!experiment.test?<button className="primary" onClick={()=>{const e=runTest(experiment);setExperiment(e);record(`最终测试：${e.test!.count} 个目标，loss ${e.test!.loss.toFixed(3)}，命中 ${(e.test!.accuracy*100).toFixed(1)}%。`);}}>打开最终测试报告</button>:<div className="journey-test-report"><span>留出测试 · {experiment.test.count} 个预测目标</span><b>loss {experiment.test.loss.toFixed(3)}</b><b>token 命中 {(experiment.test.accuracy*100).toFixed(1)}%</b><p>未知目标 {experiment.test.unknown} 个。{experiment.test.accuracy<.5?'测试中仍有很多错误。现在你得到的是一个能继续研究和改进的微型模型。':'在这批材料上已有部分预测能力；测试集很小，仍需要更多独立样本来判断泛化。'}</p></div>}<div className="journey-list"><b>实际测试材料</b>{data.test.map(r=><div key={r.id}>{r.text}</div>)}</div><p>验收后若继续训练，旧测试成绩会失效，必须重新评测。这里不模拟部署收费、GPU 时间或商业大模型能力。</p></section>}
        {stage===11&&experiment&&<section className="journey-card"><div className="journey-card-title"><h3>{config.name}</h3><span>你的微型 Transformer</span></div><div className="journey-model-card"><dl><div><dt>模型类型</dt><dd>实际训练的微型因果语言模型</dd></div><div><dt>结构</dt><dd>1 层 / 1 头 / {config.width} 维 / {config.context} token</dd></div><div><dt>参数与词表</dt><dd>{experiment.model.weights.length.toLocaleString()} 个参数 / {tokenizer.vocab.length} token</dd></div><div><dt>材料</dt><dd>{config.packs.map(id=>PACKS.find(p=>p.id===id)!.label).join('、')} · 保留 {data.clean.length} 句</dd></div><div><dt>训练经历</dt><dd>预训练 {experiment.pretrainSteps} 步；SFT {experiment.sftSteps} 步</dd></div><div><dt>最终测试</dt><dd>{experiment.test?`loss ${experiment.test.loss.toFixed(3)}；token 命中 ${(experiment.test.accuracy*100).toFixed(1)}%`:'尚未验收'}</dd></div><div><dt>偏好附件</dt><dd>{experiment.preferences.length} 组标注；候选策略 {experiment.preferenceUpdates} 次更新</dd></div></dl><p>能力边界：仅学习少量预设材料，没有通用对话、知识检索或可靠推理能力。此文件是教育实验档案，不是商业大语言模型权重。</p></div><fieldset><legend>测试自己的模型 · 预设输入（助手提问是已训练示范题）</legend><button className={testMode==='assistant'?'selected':''} aria-pressed={testMode==='assistant'} onClick={()=>setTestMode('assistant')}>助手提问</button><button className={testMode==='completion'?'selected':''} aria-pressed={testMode==='completion'} onClick={()=>setTestMode('completion')}>文本续写</button></fieldset>{testMode==='assistant'?<><div className="journey-choice">{DIALOGUES.map((d,i)=><button className={dialogue===i?'selected':''} key={d.question} onClick={()=>setDialogue(i)}>{d.question}</button>)}</div><p>用户：{DIALOGUES[dialogue].question}</p><ActualOutput experiment={experiment} prefix={`问：${DIALOGUES[dialogue].question}答：`} assistant/></>:<><div className="journey-choice">{[goal.prompt,'小猫喜欢','今天下雨，我们','小明喜欢'].filter((v,i,a)=>a.indexOf(v)===i).map(p=><button className={actualPrompt===p?'selected':''} key={p} onClick={()=>setPrompt(p)}>{p}</button>)}</div><ActualOutput experiment={experiment} prefix={actualPrompt}/></>}<div className="journey-actions"><button className="primary" onClick={()=>{exportFile(experiment);setCompleted(c=>[...new Set([...c,11])]);record(`已导出 ${config.name}：模型权重、Adam 状态、词表、配置、记录和源码。`);}}><Download size={16}/>保存我的模型文件</button><button onClick={()=>importRef.current?.click()}><Upload size={16}/>导入继续实验</button></div><p>下载 JSON 文件保存到自己的设备，之后在本页导入恢复。页面内的实验是临时状态，刷新前请先导出；恢复需要这份文件。</p><details className="journey-log-details"><summary>查看完整实验记录</summary>{experiment.logs.map((line,i)=><p key={i}>{line}</p>)}</details></section>}
        {experiment&&[6,7,8,10,11].includes(stage)&&<JourneyDiagnostics experiment={experiment} onGo={go} onRestore={restore} full={stage===7}/>}
        {!experiment&&stage>=6&&<section className="journey-card"><p>先在「搭建模型」执行初始化，再开始训练。</p><button onClick={()=>go(5)}>返回搭建模型</button></section>}
      </div></div>
      <div className="journey-navigation"><button disabled={stage===0} onClick={()=>go(stage-1)}><ChevronLeft size={15}/>上一步</button><span>{String(stage+1).padStart(2,'0')} / 12 · {current.en}</span>{stage<11?<button className="primary" disabled={!nextAllowed} onClick={next}>下一步：{stages[stage+1].title}<ChevronRight size={15}/></button>:<button onClick={rebuild}><RotateCcw size={15}/>保留结果，再造一个模型</button>}</div><footer className="journey-footer"><FlaskConical size={16}/><span>真实微型模型训练与 SFT · 偏好阶段为有限候选教学实验 · 所有训练在浏览器本地计算</span><a href="/training">回到训练原理实验室</a></footer>
    </main></div>;
}
