"use client";
import {useEffect,useMemo,useState} from 'react';
import {Layers3,FlaskConical,Check,Play,Pause,RotateCcw,ChevronRight,ChevronLeft,Lightbulb,BookOpen,SlidersHorizontal,CheckCircle2} from 'lucide-react';
import {CORPUS,VOCAB,SAMPLES,DEFAULT_SAMPLE,MAX_STEPS,createLearner,probabilities,sampleLoss,gradient,update,meanLoss,snapshot,GROUPS,PARAMETER_COUNT,QUESTIONS,FEATURE_LABELS,trainReward,reward,preferenceLoss,REFERENCE,softmax,kl,objective,policyUpdate} from '@/lib/training/engine';
import {TransformerTrace,ParameterView,TrainedGeneration} from './training-transformer';
import type {Learner,Measurement,Snapshot,Preference,Sample} from '@/lib/training/engine';

const chapters=[
  {title:'训练材料',en:'Data & Tokens',goal:'看见文本怎样提供训练答案',description:'先有材料，再有学习。这里用字符级 token，把每个预测位置拆开给你看。',tip:'真实语言模型的 token 可能是字、词或子词。这里按字切分，只是为了让每个数字都能追踪。'},
  {title:'随机初始化',en:'Random Weights',goal:'一个还没学过这些句子的模型',description:'参数先从固定种子的随机小数开始。概率不是系统猜出的台词，而是这些参数经过 Softmax 的实际结果。',tip:'概率来自实际 Transformer 前向计算。字符和位置 Embedding、注意力、前馈网络与词表投影都参与预测。'},
  {title:'亲手训练一步',en:'Predict · Learn · Update',goal:'让误差真的改变下一次预测',description:'先预测，再用文本里的正确 token 算损失。梯度告诉参数如何变化，优化器执行更新。',tip:'给正确答案的概率越低，loss 越大。即使采样碰巧选对了 token，也不意味着 loss 为零。'},
  {title:'训练与存档',en:'Training & Checkpoints',goal:'把一次更新重复很多次',description:'自动轮流读取语料中的训练样本，用相同规则重复更新。曲线是固定训练集的实际平均交叉熵。',tip:'所有前缀共享 Transformer 参数。训练后的权重也用于下方真实续写，但小语料上的表现不能证明通用语言能力。'},
  {title:'学会当助手',en:'Supervised Fine-Tuning',goal:'用示范回答进行监督微调',description:'SFT 使用整理好的对话示范。问题提供上下文，助手的示范回答提供训练目标。',tip:'这里展示常见的 assistant-only loss 设置。SFT 会训练参数，不只是给回复套一个格式。'},
  {title:'人类偏好训练',en:'RLHF',goal:'偏好、评分器和策略各司其职',description:'先比较回答，再训练一个预测偏好的评分器，最后根据奖励调整回答倾向。三个环节是分开的。',tip:'喜欢不等于事实正确。这里的评分器只用了少量人工教学特征，策略只在四个预设回答之间选择。'},
  {title:'训练 vs 生成',en:'Connect the Dots',goal:'现在把整个过程串起来',description:'训练会用目标答案计算误差并更新权重；普通生成固定权重，选择下一个 token，再把它追加到上下文。',tip:'日常发送一条聊天消息，并不会在这个演示里触发模型权重更新。'},
];
type Run={model:Learner;curve:Measurement[];snapshots:Snapshot[]};
function initialRun():Run{const m=createLearner();const s=snapshot(m);return{model:m,curve:[{step:0,loss:s.loss}],snapshots:[s]};}
function advance(run:Run,count:number,lr:number,chosen?:Sample):Run{
  let model=run.model;const curve=run.curve.slice();const snapshots=run.snapshots.slice();
  for(let i=0;i<count&&model.step<MAX_STEPS;i++){
    model=update(model,chosen??SAMPLES[model.step%SAMPLES.length],lr);
    if(model.step%20===0||chosen){curve.push({step:model.step,loss:meanLoss(model)});}
    if(model.step%400===0)snapshots.push(snapshot(model));
  }
  return{model,curve,snapshots};
}
function Badge({actual=false,children}:{actual?:boolean;children?:React.ReactNode}){return <span className={actual?'train-badge actual':'train-badge'}>{actual?'实际计算':children??'概念演示'}</span>;}
function Probabilities({values,target,baseline}:{values:number[];target?:number;baseline?:number[]}){
  const indexes=values.map((_,i)=>i).sort((a,b)=>values[b]-values[a]).slice(0,5);
  if(target!==undefined&&!indexes.includes(target))indexes.push(target);
  const other=1-indexes.reduce((sum,i)=>sum+values[i],0);
  return <div className="train-probabilities">{indexes.map(i=><div className={i===target?'target':''} key={i}><span>{VOCAB[i]}{i===target&&<small>目标</small>}</span><div className="train-bar-track">{baseline&&<i className="previous-bar" style={{width:baseline[i]*100+'%'}}/>}<i style={{width:values[i]*100+'%'}}/></div><code>{(values[i]*100).toFixed(2)}%</code></div>)}<div className="other"><span>其他</span><div className="train-bar-track"><i style={{width:Math.max(0,other)*100+'%'}}/></div><code>{(Math.max(0,other)*100).toFixed(2)}%</code></div></div>;
}
function LossChart({points,marker}:{points:Measurement[];marker?:number}){
  const max=Math.max(1,...points.map(p=>p.loss))*1.12;const last=Math.max(20,points[points.length-1].step);
  const x=(n:number)=>54+n/last*530;const y=(n:number)=>176-n/max*144;
  return <div className="train-loss-chart"><svg viewBox="0 0 620 218" role="img" aria-label={`训练集平均损失曲线，从 ${points[0].loss.toFixed(3)} 到 ${points[points.length-1].loss.toFixed(3)}`}>
    {[0,.5,1].map(n=><g key={n}><line x1="54" x2="584" y1={y(max*n)} y2={y(max*n)} stroke="#e7ecf5"/><text x="42" y={y(max*n)+4} textAnchor="end">{(max*n).toFixed(1)}</text></g>)}
    <path d={points.map((p,i)=>(i?'L':'M')+x(p.step)+','+y(p.loss)).join(' ')} stroke="#596be7" strokeWidth="2.5" fill="none"/>
    {points.length===1&&<circle cx="54" cy={y(points[0].loss)} r="4" fill="#596be7"/>}
    {marker!==undefined&&<line x1={x(marker)} x2={x(marker)} y1="20" y2="180" stroke="#e3a145" strokeDasharray="4 4"/>}
    <text x="54" y="204">0</text><text x="584" y="204" textAnchor="end">{last} step</text>
  </svg><p>固定训练集 · 平均交叉熵 <b>{points[points.length-1].loss.toFixed(3)}</b></p></div>;
}
function Tokens({text,target=false}:{text:string;target?:boolean}){return <div className={target?'train-tokens assistant':'train-tokens'}>{Array.from(text).map((t,i)=><span key={i}>{t}<small>{VOCAB.indexOf(t)>=0?'#'+VOCAB.indexOf(t):'示意'}</small></span>)}</div>;}
function SFTLesson(){
  const[q,setQ]=useState(0);const[phase,setPhase]=useState(0);const item=QUESTIONS[q];const labels=['查看对话示范','选择回答 token','观察监督训练','比较训练前后'];
  return <div className="train-sft"><div className="train-choice-row">{QUESTIONS.map((itemQ,i)=><button key={itemQ.question} className={i===q?'selected':''} aria-pressed={i===q} onClick={()=>{setQ(i);setPhase(0);}}>{itemQ.question}</button>)}</div>
    <section className="train-card"><div className="train-card-heading"><h2>对话也能提供训练答案</h2><Badge>概念演示</Badge></div><div className="train-dialog"><div><span>USER · 上下文</span><p>{item.question}</p></div><div className={phase>0?'assistant active':'assistant'}><span>ASSISTANT · 示范回答{phase>0?' · 参与 loss':''}</span><p>{item.answer}</p>{phase>0&&<Tokens text={item.answer} target/>}</div></div>
    <div className="sft-flow">{labels.map((l,i)=><span className={i<=phase?'active':''} key={l}>{i<phase?<Check size={16}/>:i+1} {l}</span>)}</div>
    {phase===0&&<p className="train-callout">这次不只是续写普通文本，而是模仿一条整理好的助手回答。</p>}
    {phase===1&&<p className="train-callout">本例只在助手回答位置计算监督损失。问题仍然是模型能看见的上下文。</p>}
    {phase===2&&<div className="sft-update"><span>示范回答</span><ChevronRight size={18}/><span>预测回答 token</span><ChevronRight size={18}/><span>loss 与梯度</span><ChevronRight size={18}/><span>更新模型参数</span><p>训练提高示范回答的似然。这是流程动画，本页没有运行完整 Transformer 微调。</p></div>}
    {phase===3&&<div className="sft-comparison"><div><span>BASE · 预设续写样例</span><p>{item.base}</p></div><div><span>SFT · 预设助手样例</span><p>{item.answer}</p></div></div>}
    <div className="train-actions"><button onClick={()=>setPhase(0)}><RotateCcw size={15}/>重看示范</button><button className="primary" disabled={phase===3} onClick={()=>setPhase(v=>Math.min(3,v+1))}>{phase===0?'看看训练目标':phase===1?'模仿示范回答':phase===2?'看看回复变化':'已完成这组示范'}</button></div></section><div className="train-small-note"><Lightbulb size={17}/><p>SFT 仍使用下一个 token 的监督信号。它改变回答方式，也可能学习新内容；不能把它理解成只改语气。</p></div></div>;
}
function RLHFLesson(){
  const[q,setQ]=useState(0);const[pair,setPair]=useState(0);const[prefs,setPrefs]=useState<Preference[]>([]);const[w,setW]=useState([0,0,0,0]);const[trained,setTrained]=useState(false);const[rmBefore,setRmBefore]=useState<number|null>(null);const[logits,setLogits]=useState(REFERENCE.map(Math.log));const[iterations,setIterations]=useState(0);const[beta,setBeta]=useState(.25);const[profile,setProfile]=useState('mine');const[stage,setStage]=useState(0);
  const candidates=QUESTIONS[q].candidates;const activeW=profile==='praise'?[.1,.1,0,4]:profile==='quality'?[2,2,1,0]:w;
  const scores=candidates.map(c=>reward(c.features,activeW));const p=softmax(logits);const ready=profile!=='mine'||trained;
  const left=0,right=pair+1;
  const resetPolicy=()=>{setLogits(REFERENCE.map(Math.log));setIterations(0);};
  const choose=(winner:number|null)=>{if(winner!==null){setPrefs(v=>[...v,{question:q,chosen:winner,rejected:winner===left?right:left}]);setTrained(false);setRmBefore(null);setW([0,0,0,0]);resetPolicy();}setPair(v=>(v+1)%3);};
  const resetAll=()=>{setPrefs([]);setW([0,0,0,0]);setTrained(false);setRmBefore(null);setProfile('mine');setPair(0);setStage(0);resetPolicy();};
  return <div className="train-rlhf"><div className="rlhf-route">{['人类比较','训练评分器','优化回答倾向'].map((s,i)=><button className={stage===i?'selected':''} aria-pressed={stage===i} key={s} onClick={()=>setStage(i)}><span>0{i+1}</span>{s}</button>)}</div>
  <div className="train-choice-row">{QUESTIONS.map((item,i)=><button key={i} className={q===i?'selected':''} aria-pressed={q===i} onClick={()=>{setQ(i);setPair(0);resetPolicy();}}>{item.question}</button>)}</div>
  {stage===0&&<section className="train-card"><div className="train-card-heading"><h2>你更喜欢哪一个回答？</h2><Badge>预设候选 · 真实记录选择</Badge></div><p className="train-copy">同一个问题，比较两条回答。你的选择会改变下一步训练出来的评分器。</p><div className="preference-cards">{[left,right].map((index,i)=><button key={index} onClick={()=>choose(index)}><span>回答 {String.fromCharCode(65+index)}</span><p>{candidates[index].text}</p><b>更喜欢这条 <Check size={16}/></b><small>{i===0?'候选一':'候选二'}</small></button>)}</div><div className="preference-bottom"><button onClick={()=>choose(null)}>差不多，跳过这组</button><span>已记录 <b>{prefs.length}</b> 组偏好</span></div><details className="train-details"><summary>查看我的选择</summary>{prefs.length?prefs.map((pref,i)=><div className="preference-record" key={i}><span>{QUESTIONS[pref.question].question} · {String.fromCharCode(65+pref.chosen)} 优于 {String.fromCharCode(65+pref.rejected)}</span><button onClick={()=>{setPrefs(v=>v.filter((_,j)=>j!==i));setW([0,0,0,0]);setTrained(false);setRmBefore(null);resetPolicy();}}>撤销</button></div>):<p>还没有偏好数据。跳过不会产生训练标签。</p>}</details><div className="train-actions"><button onClick={resetAll}><RotateCcw size={15}/>重新标注</button><button className="primary" disabled={!prefs.length} onClick={()=>setStage(1)}>用这些偏好训练评分器</button></div></section>}
  {stage===1&&<section className="train-card"><div className="train-card-heading"><h2>先教会一个小型评分器</h2><Badge actual/></div><p className="train-copy">评分器用「相关、事实质量、简洁、奉承」四项人工教学特征，学习你的比较。真实奖励模型通常从文本表示中学习。</p><div className="reward-weights">{FEATURE_LABELS.map((label,i)=><div key={label}><span>{label}</span><b>{w[i].toFixed(3)}</b><small>学习到的特征权重</small></div>)}</div><div className="reward-table">{candidates.map((c,i)=><div key={i}><span>{String.fromCharCode(65+i)} · {c.text}</span><code>{reward(c.features,w).toFixed(3)}</code></div>)}</div><div className="train-callout">{!prefs.length?'先比较回答，提供一些偏好数据。':trained?`偏好损失：${rmBefore?.toFixed(3)} → ${preferenceLoss(w,prefs).toFixed(3)}。这些分数是相对偏好信号，不是正确率。`:`已有 ${prefs.length} 组比较。接下来用梯度下降更新评分器的参数。`}</div><details className="train-details"><summary>看看评分器怎么算</summary><p>回答分数 = 四个特征与对应权重的乘积之和。每对偏好的损失 = −log σ(喜欢的分数 − 不喜欢的分数)。</p><p>点击训练执行 30 次实际梯度更新。少量选择不能代表所有人的价值观。</p></details><div className="train-actions"><button onClick={()=>setStage(0)}>返回标注</button><button className="primary" disabled={!prefs.length} onClick={()=>{setRmBefore(preferenceLoss(w,prefs));setW(trainReward(w,prefs));setTrained(true);resetPolicy();}}>训练评分器 · 30 次更新</button><button disabled={!trained} onClick={()=>setStage(2)}>继续策略优化</button></div></section>}
  {stage===2&&<section className="train-card"><div className="train-card-heading"><h2>高分回答，会变得更容易被选择</h2><Badge actual/></div><p className="train-copy">在四个候选回答上优化一个小型概率策略。这是在演示奖励怎样影响倾向，没有执行完整 PPO 或 LLM 训练。</p><label className="train-select-label">选择评分规则<select value={profile} onChange={e=>{setProfile(e.target.value);resetPolicy();}}><option value="mine">我训练的评分器</option><option value="quality">预设：重视相关与准确</option><option value="praise">预设：过度奖励奉承</option></select></label>{profile==='praise'&&<p className="train-callout amber">这条评分规则人为过度奖励奉承。观察它怎样把概率推向夸张的回答。</p>}{!ready&&<p className="train-callout">先训练你的评分器，或选择一个预设规则进行比较。</p>}
  <div className="policy-table">{candidates.map((c,i)=><div key={i}><div><span>回答 {String.fromCharCode(65+i)}</span><p>{c.text}</p></div><div className="policy-score"><small>奖励</small><b>{scores[i].toFixed(2)}</b></div><div className="policy-prob"><div className="train-bar-track"><i className="previous-bar" style={{width:REFERENCE[i]*100+'%'}}/><i style={{width:p[i]*100+'%'}}/></div><code>{(p[i]*100).toFixed(1)}%</code><small>原 {(REFERENCE[i]*100).toFixed(0)}%</small></div></div>)}</div>
  <div className="train-metrics three"><div><span>优化次数</span><b>{iterations}</b></div><div><span>期望奖励</span><b>{p.reduce((sum,v,i)=>sum+v*scores[i],0).toFixed(3)}</b></div><div><span>偏离参考 · KL</span><b>{kl(p).toFixed(3)}</b></div></div><details className="train-details"><summary>看看优化目标与 KL</summary><p>目标 J = 期望奖励 − β × KL(当前策略 || 参考策略)。J = {objective(logits,scores,beta).toFixed(3)}。</p><label className="train-range-label">β · 偏离参考的代价 <b>{beta.toFixed(2)}</b><input type="range" min="0" max="2" step=".05" value={beta} onChange={e=>setBeta(Number(e.target.value))}/></label><p>参考策略保留 SFT 阶段的候选分布，并保持冻结。KL 限制偏离程度，不保证答案真实或安全。</p><p>经典 RLHF 可用 PPO 优化；这里使用有限候选上的目标梯度。DPO 是另一条可直接使用偏好对的路线。</p></details>
  <div className="train-actions"><button onClick={resetPolicy}><RotateCcw size={15}/>重置策略</button><button className="primary" disabled={!ready||iterations>=100} onClick={()=>{let next=logits;const count=Math.min(10,100-iterations);for(let i=0;i<count;i++)next=policyUpdate(next,scores,beta);setLogits(next);setIterations(v=>v+count);}}>按奖励优化 · 10 次</button><button onClick={()=>setStage(1)}>回到评分器</button></div></section>}
  <div className="train-small-note"><Lightbulb size={17}/><p>评分器训练和回答策略训练发生在不同环节。评分高，不等于事实一定正确，更不等于已经解决对齐。</p></div></div>;
}
function FinishLesson(){const[answer,setAnswer]=useState<(number|null)[]>([null,null,null]);const quizzes=[{q:'聊天时，模型每收到一句话就更新权重吗？',options:['会','通常不会'],right:1,why:'普通推理使用固定权重。对话上下文改变，不等于训练参数改变。'},{q:'采样碰巧选对 token，loss 就一定为零吗？',options:['一定','不一定'],right:1,why:'loss 取决于目标 token 的概率，−ln(p)。抽中目标不代表概率等于 1。'},{q:'奖励分数提高，回答一定更真实吗？',options:['一定','不一定'],right:1,why:'奖励是评分器的信号。评分器可能学到有偏或不完整的偏好。'}];
  return <><section className="train-card"><div className="train-card-heading"><h2>同样计算概率，用途不同</h2><BookOpen size={20}/></div><div className="train-table-wrap"><table className="train-compare-table"><thead><tr><th>观察项</th><th>训练</th><th>生成 / 推理</th></tr></thead><tbody>{[['输入','文本里的真实前缀','prompt 和已经生成的 token'],['目标 token','来自训练文本','每一步没有标准答案'],['loss','用目标概率计算','普通生成不计算训练损失'],['反向传播','计算梯度','不执行'],['模型参数','优化器更新','保持固定'],['下一步','继续读取训练样本','采样并追加下一个 token']].map(row=><tr key={row[0]}>{row.map((v,i)=><td key={i}>{v}</td>)}</tr>)}</tbody></table></div><p className="train-copy">真实自回归训练可以在多个位置并行计算误差；本页逐位置显示，是为了方便观察。生成时则把新 token 接回上下文。</p><div className="train-bridges"><a href="/"><Layers3 size={22}/><div><b>Transformer 怎样算出概率？</b><span>原有 Encoder 示例，使用独立的固定权重</span></div></a><a href="/generation"><Play size={22}/><div><b>固定权重怎样生成文字？</b><span>原有 Decoder 示例，使用独立的固定权重</span></div></a></div></section><section className="train-card"><div className="train-card-heading"><h2>三个小问题，检查一下理解</h2><Badge>可跳过</Badge></div>{quizzes.map((quiz,i)=><div className="train-quiz" key={i}><p>{i+1}. {quiz.q}</p><div className="train-choice-row">{quiz.options.map((o,j)=><button key={o} className={answer[i]===j?'selected':''} aria-pressed={answer[i]===j} onClick={()=>setAnswer(v=>v.map((a,k)=>k===i?j:a))}>{o}</button>)}</div>{answer[i]!==null&&<p className={answer[i]===quiz.right?'quiz-result correct':'quiz-result'}>{answer[i]===quiz.right?'对。':'再想一下。'}{quiz.why}</p>}</div>)}</section><div className="train-summary"><div><b>预训练</b><span>从文本学习预测</span></div><div><b>SFT</b><span>模仿助手示范</span></div><div><b>RLHF</b><span>根据偏好调整倾向</span></div></div></>;
}
export default function TrainingLab(){
  const[chapter,setChapter]=useState(0);const[run,setRun]=useState<Run>(initialRun);const[selected,setSelected]=useState(DEFAULT_SAMPLE);const[phase,setPhase]=useState(0);const[transaction,setTransaction]=useState<Learner|null>(null);const[running,setRunning]=useState(false);const[speed,setSpeed]=useState(1);const[lr,setLr]=useState(.003);const[view,setView]=useState<Snapshot|null>(null);const[initialized,setInitialized]=useState(false);
  const sample=SAMPLES[selected];const displayed=view??run.model;const probs=probabilities(displayed,sample);
  const before=transaction??run.model;const beforeP=probabilities(before,sample);const g=useMemo(()=>chapter===2&&phase>=3?gradient(before,sample):[],[before,sample,chapter,phase]);const lesson=chapters[chapter];
  const nav=(n:number)=>{setRunning(false);setView(null);setPhase(0);setTransaction(null);setChapter(n);};
  const reset=()=>{setRunning(false);setRun(initialRun());setPhase(0);setTransaction(null);setView(null);setInitialized(true);};
  const select=(n:number)=>{setRunning(false);setSelected(n);setPhase(0);setTransaction(null);};
  useEffect(()=>{if(!running||chapter!==3||view||run.model.step>=MAX_STEPS)return;const timer=setTimeout(()=>setRun(v=>advance(v,20,lr)),550/speed);return()=>clearTimeout(timer);},[running,chapter,view,run.model.step,lr,speed]);
  useEffect(()=>{if(run.model.step>=MAX_STEPS)setRunning(false);},[run.model.step]);
  const activeSnapshot=useMemo(()=>snapshot(run.model),[run.model]);const allSnapshots=[...run.snapshots.filter(s=>s.step!==activeSnapshot.step),activeSnapshot];
  const currentSentence=CORPUS[sample.sentence];
  const phases=['取一个样本','计算预测','计算 loss','计算梯度','更新参数','再次检查'];
  const manualNext=()=>{if(phase===5){select((selected+1)%SAMPLES.length);return;}if(phase===0)setTransaction(run.model);if(phase===4)setRun(v=>advance(v,1,lr,sample));setPhase(v=>v+1);};
  return <div className="lab training-lab"><header className="topbar"><a className="brand" href="/"><span className="brand-icon"><Layers3 size={23}/></span>Transformer <span className="brand-light">Lab</span></a><nav className="mode-nav" aria-label="学习模式"><a href="/">Transformer 层内流程</a><a href="/generation">LLM 生成模式</a><a href="/training">PyTorch 训练</a><a href="/build-model">从零造模</a></nav><span className="training-header-mark"><FlaskConical size={18}/> TRAIN / 03</span></header>
  <aside className="sidebar training-sidebar"><div className="section-label">模型的学习路径</div><h3>从数据，到助手</h3><nav aria-label="训练章节">{chapters.map((c,i)=><button key={c.title} className={chapter===i?'step active':i<chapter?'step completed':'step'} aria-current={chapter===i?'step':undefined} onClick={()=>nav(i)}><span className="step-number">{i<chapter?<Check size={13}/>:String(i+1).padStart(2,'0')}</span><span>{c.title}<small>{c.en}</small></span>{i===chapter&&<ChevronRight size={16}/>}</button>)}</nav><div className="training-sidebar-note"><FlaskConical size={20}/><b>先动手，再看公式</b><p>小型数值实验与预设句子，让每次更新都有迹可循。</p><span>本地计算 · 无需输入</span></div></aside>
  <main className="main training-main"><div className="page-heading"><div><div className="eyebrow">MODEL TRAINING LAB</div><h1>模型，<span>是怎样学会的？</span></h1><p className="intro">用预设句子，亲手体验从预测到参数更新，再到助手训练。</p></div><span className="model-label"><FlaskConical size={16}/> 从数据到助手</span></div>
  <a className="training-grokking-entry" href="/build-model"><span>完整项目</span><div><b>从零创建自己的模型</b><small>看真实代码，选数据、训练、微调、验收，最后导出自己的权重。</small></div><FlaskConical size={21}/></a><p className="tiny-disclosure">前四章使用同一个微型 Transformer：前向预测、反向传播、Adam 更新、存档与续写共用权重。SFT、RLHF 和泛化专题仍是另外的教学演示。</p><a className="training-grokking-entry" href="/training/grokking"><span>泛化专题</span><div><b>背下答案，还是学会规律？</b><small>训练题先满分，新题为何还不会？用曲线、同题存档与记忆对照亲手观察。</small></div><FlaskConical size={21}/></a><nav className="train-mobile-chapters" aria-label="训练章节快捷入口">{chapters.map((c,i)=><button key={c.title} aria-current={chapter===i?'step':undefined} className={chapter===i?'selected':''} onClick={()=>nav(i)}>{String(i+1).padStart(2,'0')} {c.title}</button>)}</nav>
  <div className="train-lesson-heading"><span>0{chapter+1} / 07</span><div><h2>{lesson.goal}</h2><p>{lesson.description}</p></div></div>
  <div className={chapter<4?'train-studio':'train-studio advanced'}><div className="train-primary-column">
  {chapter===0&&<section className="train-card"><div className="train-card-heading"><h2>模型在读什么？</h2><span className="train-badge">{CORPUS.length} 句 · {VOCAB.length} 个字符 token</span></div><div className="corpus-selector">{CORPUS.map((text,i)=><button key={text} className={i===sample.sentence?'selected':''} aria-pressed={i===sample.sentence} onClick={()=>select(SAMPLES.findIndex(s=>s.sentence===i))}>{text}</button>)}</div><div className="train-section-label">文本变成 token 与编号</div><Tokens text={currentSentence}/><div className="train-position-label"><label htmlFor="training-position">选择一个预测位置</label><span>{sample.position} / {Array.from(currentSentence).length-1}</span></div><input id="training-position" className="train-position" type="range" min="1" max={Array.from(currentSentence).length-1} value={sample.position} onChange={e=>select(SAMPLES.findIndex(s=>s.sentence===sample.sentence&&s.position===Number(e.target.value)))}/><div className="sample-pair"><div><span>给模型的前缀</span><b>{sample.prefix}</b></div><ChevronRight size={22}/><div className="target"><span>文本中的下一个 token</span><b>{VOCAB[sample.target]}</b></div></div><p className="train-callout">答案就在原文里。沿着同一句话，可以拆出多个「前缀 → 下一个 token」训练样本。</p><details className="train-details"><summary>看看一整段怎样对齐</summary><div className="shifted-tokens"><span>输入</span><Tokens text={Array.from(currentSentence).slice(0,-1).join('')}/><span>目标</span><Tokens text={Array.from(currentSentence).slice(1).join('')} target/></div><p>完整训练可以并行计算多个位置的损失。这里逐位置展示，便于你观察。</p></details></section>}
  {chapter===1&&<section className="train-card"><div className="train-card-heading"><h2>先从一堆数字开始</h2><Badge actual/></div><div className="train-actions"><button className="primary" onClick={reset}><RotateCcw size={16}/>{initialized?'重新初始化模型':'初始化模型'}</button><span className="train-muted">固定种子 · 重置可复现</span></div><div className="train-metrics"><div><span>训练 step</span><b>{run.model.step}</b></div><div><span>当前样本 loss</span><b>{sampleLoss(run.model,sample).toFixed(3)}</b></div></div><div className="train-section-label">Transformer 的可训练参数 · 共 {PARAMETER_COUNT} 项</div><ParameterView model={run.model}/><TransformerTrace model={run.model} prefix={sample.prefix}/><div className="train-section-label">下一个 token 的概率</div><Probabilities values={probs} target={sample.target}/><p className="train-muted">这些概率来自上方 Transformer 的词表投影，并非给每个前缀单独存一张概率表。</p></section>}
  {chapter===2&&<section className="train-card"><div className="train-card-heading"><h2>把一次训练拆开看</h2><Badge actual/></div><div className="train-choice-row">{['小猫喜欢','今天下雨，我们带','你好'].map(prefix=><button key={prefix} aria-pressed={sample.prefix===prefix} className={sample.prefix===prefix?'selected':''} onClick={()=>select(SAMPLES.findIndex(s=>s.prefix===prefix))}>{prefix}</button>)}</div><div className="training-phases">{phases.map((p,i)=><span key={p} className={i===phase?'active':i<phase?'done':''}><b>{i<phase?<Check size={14}/>:i+1}</b>{p}</span>)}</div><div className="sample-pair"><div><span>输入前缀</span><b>{sample.prefix}</b></div><ChevronRight size={22}/><div className="target"><span>真实目标</span><b>{VOCAB[sample.target]}</b></div></div>
  {phase===0&&<div className="train-callout">从「{currentSentence}」中取出这个训练样本。点击下方按钮，先用当前参数预测。</div>}
  {phase>=1&&<TransformerTrace model={phase===5?run.model:before} prefix={sample.prefix} previous={phase===5?before:undefined}/>}
  {phase>=1&&<Probabilities values={phase===5?probs:beforeP} target={sample.target} baseline={phase===5?beforeP:undefined}/>}
  {phase===1&&<p className="train-callout">前缀经过 Embedding、因果注意力、前馈网络、归一化与词表投影，得到 logits，再用 Softmax 转成概率。模型给「{VOCAB[sample.target]}」的概率是 {(beforeP[sample.target]*100).toFixed(2)}%。</p>}
  {phase>=2&&<div className="loss-equation"><span>目标概率 p</span><b>{beforeP[sample.target].toFixed(4)}</b><ChevronRight size={20}/><span>−ln(p)</span><b>{sampleLoss(before,sample).toFixed(3)}</b>{phase===5&&<><ChevronRight size={20}/><span>更新后 loss</span><b className="improved">{sampleLoss(run.model,sample).toFixed(3)}</b></>}</div>}
  {phase===2&&<p className="train-callout">概率越小，loss 越大。比如 10% 对应 2.30，50% 对应 0.69。</p>}
  {phase>=3&&<><div className="backprop-route"><span>loss</span><ChevronRight size={16}/><span>概率与 logits</span><ChevronRight size={16}/><span>词表投影</span><ChevronRight size={16}/><span>前馈与注意力</span><ChevronRight size={16}/><span>Embedding</span></div><ParameterView model={phase===5?run.model:before} grad={g} previous={phase===5?before:undefined}/></>}
  {phase===3&&<p className="train-callout">概率 − 目标的 one-hot 是 logits 的梯度。链式法则继续穿过词表投影、LayerNorm、前馈网络、注意力和 Embedding，得到各组参数的梯度；下一步才执行更新。</p>}
  {phase===4&&<div className="parameter-update"><code>Adam：用梯度的一阶、二阶移动平均计算参数更新</code><p>先将全局梯度范数裁剪至最多 1，再更新 Adam 的动量；使用偏差校正、β₁ = 0.9、β₂ = 0.999、ε = 10⁻⁸。学习率为 {lr.toFixed(3)}。</p><p>示例 WQ[0,0]：{before.weights[GROUPS.find(g=>g.name==='q')!.start].toFixed(5)} → {update(before,sample,lr).weights[GROUPS.find(g=>g.name==='q')!.start].toFixed(5)}（点击执行后生效）</p></div>}
  {phase===5&&<div className="train-success"><CheckCircle2 size={21}/><div><b>完成一次参数更新</b><p>目标概率 {(beforeP[sample.target]*100).toFixed(2)}% → {(probs[sample.target]*100).toFixed(2)}%。训练 step 现在是 {run.model.step}。</p><small>这里检查的是同一样本，不表示所有样本都同时改善。</small></div></div>}
  <div className="train-actions"><button onClick={()=>{setPhase(0);setTransaction(null);}}>重看当前样本</button><button className="primary" disabled={phase<5&&run.model.step>=MAX_STEPS} onClick={manualNext}>{['用参数算出预测','根据目标计算 loss','反向传播，计算梯度','看看参数如何更新','执行一次参数更新','换一个样本再试'][phase]}</button></div></section>}
  {chapter===3&&<><section className="train-card"><div className="train-card-heading"><h2>重复更新，让预测变好</h2><Badge actual/></div><div className="train-metrics three"><div><span>实际训练 step</span><b>{run.model.step}</b></div><div><span>处理样本 / 总样本</span><b className="metric-small">{run.model.step} / {SAMPLES.length}</b><small>约 {(run.model.step/SAMPLES.length).toFixed(1)} 次数据遍历</small></div><div><span>训练集平均 loss</span><b>{meanLoss(run.model).toFixed(3)}</b></div></div><LossChart points={run.curve} marker={view?.step}/><div className="train-actions"><button disabled={!!view||run.model.step>=MAX_STEPS} className="primary" onClick={()=>setRunning(v=>!v)}>{running?<Pause size={16}/>:<Play size={16}/>} {running?'暂停训练':'自动训练'}</button><button disabled={running||!!view||run.model.step>=MAX_STEPS} onClick={()=>setRun(v=>advance(v,20,lr))}>训练 20 步</button><button onClick={reset}><RotateCcw size={15}/>重置</button><label className="train-speed"><span>播放</span><select aria-label="自动训练速度" value={speed} onChange={e=>setSpeed(Number(e.target.value))}><option value=".5">慢</option><option value="1">正常</option><option value="2">快</option></select></label></div>{run.model.step>=MAX_STEPS&&<p className="train-callout">已达到本次实验 {MAX_STEPS} 步的上限。可以比较存档，或继续了解 SFT。</p>}
  <div className="train-section-label">真实权重存档 · 每 400 步保存</div><div className="checkpoint-row">{allSnapshots.map(s=><button className={(view?.step??run.model.step)===s.step?'selected':''} aria-pressed={(view?.step??run.model.step)===s.step} key={s.step} onClick={()=>{setRunning(false);setView(s.step===run.model.step?null:s);}}>Step {s.step}<small>loss {s.loss.toFixed(3)}</small></button>)}</div>{view&&<div className="checkpoint-warning">正在查看 Step {view.step} 的历史存档，当前训练权重保留。<button onClick={()=>setView(null)}>返回当前模型</button></div>}
  <div className="train-choice-row">{['小猫喜欢','今天下雨，我们带','你好'].map(prefix=><button className={sample.prefix===prefix?'selected':''} aria-pressed={sample.prefix===prefix} key={prefix} onClick={()=>select(SAMPLES.findIndex(s=>s.prefix===prefix))}>{prefix}</button>)}</div><Probabilities values={probs} target={sample.target}/><p className="train-muted">当前样本：「{sample.prefix}」→「{VOCAB[sample.target]}」· loss {sampleLoss(displayed,sample).toFixed(3)}</p></section><TransformerTrace model={displayed} prefix={sample.prefix}/><div id="trained-generation"><TrainedGeneration model={displayed} initial={run.snapshots[0]}/></div></>}
  {chapter===4&&<SFTLesson/>}{chapter===5&&<RLHFLesson/>}{chapter===6&&<><FinishLesson/><TrainedGeneration model={run.model} initial={run.snapshots[0]}/></>}
  </div><aside className="train-inspector"><div className="train-card"><div className="inspector-label"><span>理解这一步</span><span>0{chapter+1}</span></div><h3>{lesson.title}</h3><p>{lesson.description}</p><div className="train-insight"><Lightbulb size={19}/><p>{lesson.tip}</p></div>{chapter<4&&<details className="train-details"><summary><SlidersHorizontal size={15}/> 实验设置与原理</summary><label className="train-range-label">学习率 <b>{lr.toFixed(3)}</b><input type="range" min=".001" max=".01" step=".001" value={lr} disabled={(chapter===2&&phase>0&&phase<5)||!!view||running} onChange={e=>setLr(Number(e.target.value))}/></label><p>学习率决定每次更新的幅度。动画速度只影响播放节奏。</p><code>logits = Transformer(前缀; θ)<br/>p = softmax(logits)<br/>loss = −ln(p[目标])<br/>∇θ = 反向传播(loss)<br/>θ ← Adam(θ, ∇θ)</code><p>本页运行 1 层、1 个头、8 维的因果 Transformer。全部 {PARAMETER_COUNT} 个参数都可训练，包括 Embedding、Q/K/V、前馈网络、归一化与词表投影。每一步只计算前缀最后位置的 loss。</p><p>训练共享参数；新句子的泛化能力仍需独立评测，本页训练曲线不提供这种证据。</p></details>}{chapter===3&&<details className="train-details"><summary>为什么曲线不一定一直下降？</summary><p>一次更新可能让当前样本更好、另一个样本更差。同一个前缀也可能有不同的合法后续。</p><p>这里不提供验证集曲线，不能用训练曲线判断泛化。Grokking 特指某些实验里在拟合训练集较久之后才发生的泛化，和「句子突然通顺」不是同一个概念。</p></details>}{chapter===4&&<div className="train-insight"><p>预训练：普通文本提供目标。<br/>SFT：助手示范提供目标。<br/>两者都可以使用交叉熵训练。</p></div>}{chapter===5&&<div className="train-insight"><p>人类比较 → 偏好数据<br/>奖励模型 → 预测偏好分数<br/>策略优化 → 改变回答倾向</p></div>}<a className="train-related" href={chapter===6?'/generation':'/'}>{chapter===6?'打开生成模式':'看看 Transformer 前向计算'}</a></div></aside></div>
  <div className="train-navigation"><button disabled={chapter===0} onClick={()=>nav(chapter-1)}><ChevronLeft size={16}/>上一章</button><span>{chapters[chapter].en}</span>{chapter<6?<button className="primary" onClick={()=>nav(chapter+1)}>{chapter===3?'继续：SFT 教学演示':chapter===4?'继续：人类偏好训练':'下一章'}<ChevronRight size={16}/></button>:<button onClick={()=>{reset();nav(0);}}>重新体验</button>}</div>
  <footer className="page-footer"><span>微型 Transformer 实际训练与生成 · SFT 与 RLHF 为独立教学演示 · 浏览器本地运行</span><a href="https://arxiv.org/abs/2203.02155" target="_blank" rel="noreferrer">RLHF 原始论文</a></footer><span className="sr-only" role="status" aria-live="polite">当前第 {chapter+1} 章：{lesson.title}。训练步数 {run.model.step}。</span></main></div>;
}
