"use client";
import { useState } from 'react';
import { ArrowDown, ArrowRight, GitMerge, Layers3, Plus } from 'lucide-react';
import type { EncoderResult, Matrix } from '@/lib/transformer/engine';

export function Vector({ values, tone='blue' }: { values:number[]; tone?:string }) {
  return <div className={`vector ${tone}`} aria-label={values.map(x=>x.toFixed(2)).join(', ')}>{values.map((v,i)=><span key={i} title={`维度 ${i+1}: ${v.toFixed(4)}`} style={{opacity:.18+.82*Math.min(Math.abs(v)/2,1),background:v<0?'#ea997c':undefined}} />)}</div>;
}
export function MatrixView({data,rows,selected,onSelect,probability=false,tokenColumns=false,label}:{data:Matrix;rows:string[];selected:number;onSelect:(i:number)=>void;probability?:boolean;tokenColumns?:boolean;label:string}) {
  const [cell,setCell]=useState<{i:number;j:number}|null>(null);
  const cols=data[0].length;
  const hover=cell&&cell.i<data.length&&cell.j<cols?cell:{i:selected,j:0};
  return <div className="matrix-view"><div className="matrix-scroll"><div className="matrix-grid" style={{gridTemplateColumns:`64px repeat(${cols}, minmax(28px, 1fr))`}}><span className="matrix-axis">{tokenColumns?'Q ↓ / K →':'维度 →'}</span>{Array.from({length:cols},(_,i)=><span className="matrix-col" title={tokenColumns?rows[i]:undefined} key={`c${i}`}>{tokenColumns?rows[i]:`d${i+1}`}</span>)}{data.map((row,i)=><div className="matrix-row" key={i}><button className={selected===i?'matrix-label selected':'matrix-label'} onClick={()=>onSelect(i)} title={`查询 ${rows[i]}，位置 ${i}`}>{rows[i]}</button>{row.map((v,j)=><button key={j} className={`matrix-cell ${selected===i?'row-selected':''}`} aria-label={`${label}，${rows[i]} 位置 ${i}，${tokenColumns?rows[j]:`维度 ${j+1}`}：${v.toFixed(4)}`} onMouseEnter={()=>setCell({i,j})} onMouseLeave={()=>setCell(null)} onFocus={()=>setCell({i,j})} onBlur={()=>setCell(null)} onClick={()=>{onSelect(i);setCell({i,j});}} style={{background:probability?`rgba(92,107,230,${.07+v*.93})`:v<0?`rgba(229,146,111,${.10+Math.min(Math.abs(v)/2,1)*.65})`:`rgba(92,107,230,${.10+Math.min(v/2,1)*.75})`,color:(probability?v>.55:v>1.2)?'white':'#455077'}}>{probability?`${Math.round(v*100)}%`:v.toFixed(1)}</button>)}</div>)}</div></div><div className="matrix-readout"><span>{rows[hover.i]} <small>#{hover.i}</small> → {tokenColumns?`${rows[hover.j]} #${hover.j}`:`d${hover.j+1}`}</span><code>{data[hover.i][hover.j].toFixed(4)}</code><span className="legend-gradient"/>{probability?'0 → 1':'负 ← 0 → 正'}</div></div>;
}
export function Attention({model,query,head,scores,onQuery}:{model:EncoderResult;query:number;head:number;scores:boolean;onQuery:(i:number)=>void}) {
  const n=model.tokens.length;
  const values=scores?model.heads[head].scores[query]:model.heads[head].attention[query];
  const max=Math.max(...values),min=Math.min(...values);
  const x=(i:number)=> n===1?380:65+i*630/(n-1);
  return <div className="attention-scene"><div className="scene-caption"><span>QUERY / 选择查询 token</span><span>{scores?'原始匹配分数':'连线越粗，注意力越强'}</span></div><div className="query-tokens">{model.tokens.map((t,i)=><button aria-pressed={query===i} key={i} onClick={()=>onQuery(i)} className={query===i?'token selected':'token'}><small>{i}</small>{t}</button>)}</div><div className="attention-plot"><svg className="attention-svg" viewBox="0 0 760 232" role="img" aria-label={`${model.tokens[query]} 对所有 token 的${scores?'匹配分数':'注意力权重'}连线`}><defs><linearGradient id="flow-gradient" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#5b6de7"/><stop offset="100%" stopColor="#9c87e9"/></linearGradient></defs><rect x="328" y="8" width="104" height="41" rx="10" fill="#5c6de8"/><text x="380" y="34" textAnchor="middle" fill="white" fontSize="15">Q · {model.tokens[query].slice(0,7)}</text>{values.map((v,i)=>{const strength=scores?(max===min?1:(v-min)/(max-min)):v;const path=`M 380 50 C 380 111, ${x(i)} 104, ${x(i)} 166`;return <g key={`${head}-${query}-${i}`}><path d={path} stroke="url(#flow-gradient)" strokeWidth={1+strength*11} strokeOpacity={.22+strength*.72} fill="none"/><path className="flow-dash" d={path} stroke="#5b6de7" strokeWidth="1.5" strokeDasharray="4 13" fill="none" opacity={.25+strength*.6}/><rect x={x(i)-25} y="165" width="50" height="33" rx="7" fill="#fff" stroke={v===max?'#7582ed':'#dce2f1'}/><text x={x(i)} y="186" textAnchor="middle" fontSize="12" fill="#465675">{model.tokens[i].slice(0,4)}</text><text x={x(i)} y="218" textAnchor="middle" fontSize="12" fill="#7381b9">{scores?v.toFixed(2):`${(v*100).toFixed(1)}%`}</text></g>})}</svg></div><p className="mobile-pan-hint">左右滑动图表，查看全部连线</p><div className="scene-caption bottom"><span>{scores?'KEY / 匹配目标':'VALUE / 按权重收集信息'}</span><span>{scores?'分数尚未归一化':`权重总和 = ${values.reduce((a,b)=>a+b,0).toFixed(3)}`}</span></div></div>;
}
function Tile({title,subtitle,values,tone='blue'}:{title:string;subtitle:string;values?:number[];tone?:string}){return <div className={`process-tile ${tone}`}><span className="tile-symbol">{title}</span>{values&&<Vector values={values} tone={tone}/>}<small>{subtitle}</small></div>}
export function Visualization({step,model,query,head,onQuery}:{step:number;model:EncoderResult;query:number;head:number;onQuery:(i:number)=>void}) {
  const h=model.heads[head];
  if(step===5||step===6) return <Attention model={model} query={query} head={head} scores={step===5} onQuery={onQuery}/>;
  if(step===0)return <div className="overview-scene"><div className="sentence-quote">“ {model.tokens.join(' ')} ”</div><div className="overview-route"><div><span className="route-icon">Aa</span><b>文本</b><small>人类的语言</small></div><ArrowRight/><div><span className="route-icon lavender"><Layers3/></span><b>Transformer</b><small>建立上下文联系</small></div><ArrowRight/><div><span className="route-icon teal">[ y ]</span><b>向量表示</b><small>计算机的语言</small></div></div><div className="scene-note">一层 Encoder，{model.tokens.length} 个 token，一次完整的信息传递。</div></div>;
  if(step===1)return <div className="tokenization-scene"><div className="sentence-quote compact">{model.tokens.join(' ')}</div><ArrowDown className="down-arrow"/><div className="split-tokens">{model.tokens.map((t,i)=><button key={i} className={i===query?'split-token selected':'split-token'} onClick={()=>onQuery(i)} style={{animationDelay:`${i*60}ms`}}><small>POSITION {i}</small><strong>{t}</strong><code>ID {model.ids[i]}</code></button>)}</div><p className="scene-note">相同 token 共享同一个 ID；位置编号保留序列顺序。</p></div>;
  if(step===2)return <div className="embedding-scene">{model.tokens.map((t,i)=><button key={i} className={i===query?'embedding-row selected':'embedding-row'} onClick={()=>onQuery(i)}><span className="embedding-word">{t}</span><code>{model.ids[i]}</code><ArrowRight size={16}/><Vector values={model.embedding[i]}/><span className="dimension-badge">8 维</span></button>)}</div>;
  if(step===3)return <div className="equation-scene"><div className="equation-line"><Tile title="E" subtitle="词嵌入" values={model.embedding[query]}/><Plus/><Tile title="PE" subtitle={`位置 ${query} 的编码`} values={model.position[query]} tone="teal"/><ArrowRight/><Tile title="X" subtitle="包含位置信息" values={model.x[query]} tone="purple"/></div><p className="scene-note">逐元素相加，维度保持 8 维。当前 token：{model.tokens[query]}</p></div>;
  if(step===4)return <div className="qkv-scene"><Tile title="X" subtitle={`${model.tokens[query]} · 8 维`} values={model.x[query]}/><div className="branch-lines"><span/><span/><span/></div><div className="qkv-branches">{[{name:'Q',note:'查询 · 我要找什么',v:h.q[query],tone:'blue'},{name:'K',note:'键 · 我怎样被匹配',v:h.k[query],tone:'purple'},{name:'V',note:'值 · 我提供的信息',v:h.v[query],tone:'teal'}].map(p=><div className="branch" key={p.name}><code>× W{p.name}</code><ArrowRight size={18}/><Tile title={p.name} subtitle={p.note} values={p.v} tone={p.tone}/></div>)}</div></div>;
  if(step===7)return <div className="multihead-scene"><div className="heads-stack">{model.heads.map((h,i)=><div className={`head-box ${i===head?'selected':''}`} key={i}><span>HEAD {i+1}</span><Vector values={h.output[query]} tone={i?'purple':'blue'}/><small>4 维</small></div>)}</div><GitMerge className="merge-icon" size={38}/><Tile title="Concat" subtitle="拼接 · 8 维" values={model.concat[query]}/><div className="operation"><code>× WO</code><ArrowRight/></div><Tile title="M" subtitle="多头输出 · 8 维" values={model.multihead[query]} tone="purple"/></div>;
  if(step===8||step===10){const isOut=step===10;return <div className="residual-scene"><div className="skip-connection"><span>残差连接 · 保留输入</span></div><div className="equation-line"><Tile title={isOut?'H':'X'} subtitle="输入 · 8 维" values={isOut?model.norm1[query]:model.x[query]}/><Plus/><Tile title={isOut?'F':'M'} subtitle={isOut?'FFN 输出':'注意力输出'} values={isOut?model.ffn[query]:model.multihead[query]} tone="purple"/><ArrowRight/><Tile title={isOut?'Y':'H'} subtitle="LayerNorm · 8 维" values={isOut?model.output[query]:model.norm1[query]} tone="teal"/></div><p className="scene-note">{isOut?'第二次 Add & Norm 完成：每个 token 都有了上下文表示。':'先相加，再沿每个 token 的 8 个特征归一化。'}</p></div>}
  return <div className="ffn-scene"><div className="ffn-layers">{[{name:'输入 H',v:model.norm1[query]},{name:'ReLU 隐藏层',v:model.hidden[query]},{name:'输出 F',v:model.ffn[query]}].map((l,i)=><div className="ffn-layer" key={i}><span>{l.name}</span><div className="neurons">{l.v.map((v,j)=><span key={j} title={v.toFixed(4)} style={{background:v===0?'#edf0f6':`rgba(91,108,225,${.2+Math.min(Math.abs(v),2)*.4})`}}/>)}</div><small>{l.v.length} 维</small></div>)}</div><p className="scene-note">8 → 16 → 8：ReLU 将负值置零。所有 token 使用相同的网络。</p></div>;
}

